import {
  Hotel,
  PerkDeal,
  TierPlan,
  CruiseItinerary,
  AirportLounge,
  PhysicalCardOrder,
  EsimPackage,
  ProviderInstructionGuide,
  PlatformFeatureFlags,
  VisaCardAccount,
  FlightClaimRecord,
  TravelInsurancePlan,
  PrivateJetEmptyLeg,
  TripGapAlert,
  PriceDropRebookRecord,
  LuxuryYachtCharter,
  SupercarRental,
  FastTrackAirportService,
  StatusMatchProgram,
  LuxuryVillaEstate,
  TravelVaultAccount,
  NomadVisaProgram,
  NomadColivingSpace,
  SavingsProofAudit,
  LiveReceipt
} from './types';

export const MOCK_PROOF_AUDITS: SavingsProofAudit[] = [
  {
    id: 'proof-bellagio-vegas',
    hotelName: 'The Grand Bellagio & Casino Resort',
    city: 'Las Vegas, NV',
    country: 'United States',
    starRating: 5,
    dates: 'Sep 15 – Sep 18 (3 Nights)',
    nights: 3,
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    roomType: 'Deluxe Fountain View King Suite',
    publicProvider: 'Expedia',
    publicRetailPricePerNight: 389,
    publicTotalRetailPrice: 1167,
    retailMarketingMarkup: 573,
    hotelsClubWholesalePerNight: 198,
    hotelsClubTotalPaid: 594,
    instantCashSaved: 573,
    savingsPercentage: 49,
    additionalCardBonuses: {
      priceDropProtection: 168,
      travelVaultDividends: 48.50,
      visaCashback: 23.76
    },
    totalNetValueDelivered: 813.26,
    lastAuditedTimestamp: 'Today at 07:15 UTC (Real-time Bedbank Sync)',
    auditHash: '0x88f2a91...bedbank_par_ok'
  },
  {
    id: 'proof-plaza-nyc',
    hotelName: 'The Plaza Fifth Avenue',
    city: 'New York, NY',
    country: 'United States',
    starRating: 5,
    dates: 'Oct 10 – Oct 14 (4 Nights)',
    nights: 4,
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
    roomType: 'Edwardian Fifth Avenue Park Suite',
    publicProvider: 'Booking.com',
    publicRetailPricePerNight: 740,
    publicTotalRetailPrice: 2960,
    retailMarketingMarkup: 1480,
    hotelsClubWholesalePerNight: 370,
    hotelsClubTotalPaid: 1480,
    instantCashSaved: 1480,
    savingsPercentage: 50,
    additionalCardBonuses: {
      priceDropProtection: 210,
      travelVaultDividends: 118.40,
      visaCashback: 59.20
    },
    totalNetValueDelivered: 1867.60,
    lastAuditedTimestamp: 'Today at 06:42 UTC (Real-time Bedbank Sync)',
    auditHash: '0x33b1e70...hotelbeds_ver_ok'
  },
  {
    id: 'proof-ritz-paris',
    hotelName: 'Ritz Paris (Place Vendôme)',
    city: 'Paris',
    country: 'France',
    starRating: 5,
    dates: 'Nov 02 – Nov 05 (3 Nights)',
    nights: 3,
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80',
    roomType: 'Prestige Deluxe Junior Suite',
    publicProvider: 'Hotels.com',
    publicRetailPricePerNight: 1650,
    publicTotalRetailPrice: 4950,
    retailMarketingMarkup: 2250,
    hotelsClubWholesalePerNight: 900,
    hotelsClubTotalPaid: 2700,
    instantCashSaved: 2250,
    savingsPercentage: 45,
    additionalCardBonuses: {
      priceDropProtection: 340,
      travelVaultDividends: 216.00,
      visaCashback: 108.00
    },
    totalNetValueDelivered: 2914.00,
    lastAuditedTimestamp: 'Today at 05:30 UTC (Real-time Bedbank Sync)',
    auditHash: '0x99a4c12...webbeds_xml_pass'
  },
  {
    id: 'proof-villa-stbarts',
    hotelName: 'Villa L’Étoile & Private Beach Estate',
    city: 'St. Barts',
    country: 'Caribbean',
    starRating: 5,
    dates: 'Dec 18 – Dec 25 (7 Nights)',
    nights: 7,
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    roomType: '6-Bedroom Oceanfront Villa with Chef & Butler',
    publicProvider: 'Airbnb',
    publicRetailPricePerNight: 5800,
    publicTotalRetailPrice: 40600,
    retailMarketingMarkup: 18200,
    hotelsClubWholesalePerNight: 3200,
    hotelsClubTotalPaid: 22400,
    instantCashSaved: 18200,
    savingsPercentage: 45,
    additionalCardBonuses: {
      priceDropProtection: 750,
      travelVaultDividends: 1792.00,
      visaCashback: 896.00
    },
    totalNetValueDelivered: 21638.00,
    lastAuditedTimestamp: 'Today at 04:12 UTC (B2B Estate Feed)',
    auditHash: '0x77c9d44...lecoll_estate_ok'
  }
];

export const MOCK_LIVE_RECEIPTS: LiveReceipt[] = [
  {
    id: 'rec-991',
    memberNameMasked: 'Marcus V.',
    memberTier: 'gold',
    itemBooked: 'The Plaza Fifth Avenue (4 Nights)',
    destination: 'New York, NY',
    retailPrice: 2960,
    wholesalePaid: 1480,
    amountSaved: 1480,
    cashbackDepositedToVisa: 59.20,
    timestampAgo: '2 minutes ago'
  },
  {
    id: 'rec-992',
    memberNameMasked: 'Elena R.',
    memberTier: 'nomad',
    itemBooked: 'Outsite Coliving Lisbon (30 Nights)',
    destination: 'Lisbon, Portugal',
    retailPrice: 2100,
    wholesalePaid: 1150,
    amountSaved: 950,
    cashbackDepositedToVisa: 46.00,
    timestampAgo: '5 minutes ago'
  },
  {
    id: 'rec-993',
    memberNameMasked: 'Alexander H.',
    memberTier: 'platinum',
    itemBooked: 'The Grand Bellagio (3 Nights)',
    destination: 'Las Vegas, NV',
    retailPrice: 1167,
    wholesalePaid: 594,
    amountSaved: 573,
    cashbackDepositedToVisa: 23.76,
    timestampAgo: '9 minutes ago'
  },
  {
    id: 'rec-994',
    memberNameMasked: 'Sophia C.',
    memberTier: 'gold',
    itemBooked: 'Bombardier Challenger 300 Private Jet Seat',
    destination: 'Miami ➔ New York',
    retailPrice: 3800,
    wholesalePaid: 1250,
    amountSaved: 2550,
    cashbackDepositedToVisa: 50.00,
    timestampAgo: '14 minutes ago'
  }
];

export const DEFAULT_PLATFORM_CONFIG: PlatformFeatureFlags = {
  enableHotels: true,
  enableCruises: true,
  enableLounges: true,
  enableEsim: true,
  enableFlightClaims: true,
  enableTravelInsurance: true,
  enablePrivateJets: true,
  enableAutoRebooker: true,
  enableYachtsAndSupercars: true,
  enableFastTrackImmigration: true,
  enableStatusMatch: true,
  enableLuxuryVillas: true,
  enableTravelVault: true,
  enableNomadHub: true,
  enablePhysicalIdCards: true,
  enableVisaPrepaidCards: true,
  enableAiConcierge: true,
  enableProactiveTripGaps: true,
  enableElevenLabsVoice: true,
  allowMemberDirectBooking: true,
  defaultCommissionPassThrough: 100,
  lastPublishedAt: '2026-08-26 07:00 UTC',
};

export const MOCK_NOMAD_VISAS: NomadVisaProgram[] = [
  {
    id: 'visa-spain-dvn',
    country: 'Spain',
    countryCode: 'ES',
    flagEmoji: '🇪🇸',
    visaName: 'Spain Digital Nomad Visa (Ley de Startups)',
    minMonthlyIncome: '€2,646 / month (~$2,850)',
    incomeThresholdUsd: 2850,
    durationStay: '3 Years (Renewable up to 5 Years) ➔ Permanent Residency',
    taxRate: '24% Flat Tax (Beckham Law exemption on foreign income up to €600k)',
    isZeroTax: false,
    processingTime: '20 Business Days via UGE Fast-Track',
    cost: 80,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Proof of remote employment or remote freelancing contracts (minimum 3 months tenure)',
      'University degree or 3+ years verified professional experience',
      'Clean criminal record certificate (with Hague Apostille)',
      'Private Health Insurance with full Spain coverage ($0 copay)'
    ],
    popularHubs: ['Barcelona', 'Madrid', 'Valencia', 'Málaga', 'Las Palmas (Canary Islands)', 'Alicante', 'Seville'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-portugal-d8',
    country: 'Portugal',
    countryCode: 'PT',
    flagEmoji: '🇵🇹',
    visaName: 'Portugal D8 Digital Nomad Visa',
    minMonthlyIncome: '€3,280 / month (4x Portuguese Minimum Wage)',
    incomeThresholdUsd: 3500,
    durationStay: '1 Year Temporary Stay OR 2-Year Renewable Residence Permit',
    taxRate: '20% Flat Rate under NHR 2.0 / Standard Tiered Rates',
    isZeroTax: false,
    processingTime: '30 – 60 Days via AIMA',
    cost: 90,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Remote work contract or active freelance client contracts',
      'Bank statements showing last 3 months average income above €3,280/mo',
      'Portuguese NIF tax number and proof of local accommodation (Lease or Coliving)',
      'Clean police record and international travel health insurance'
    ],
    popularHubs: ['Lisbon', 'Porto', 'Madeira Island (Nomad Village Ponta do Sol)', 'Ericeira', 'Lagos (Algarve)', 'Braga'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-italy-dvn',
    country: 'Italy',
    countryCode: 'IT',
    flagEmoji: '🇮🇹',
    visaName: 'Italy Digital Nomad Visa (Art. 27-quater)',
    minMonthlyIncome: '€2,333 / month (~€28,000 / year)',
    incomeThresholdUsd: 2500,
    durationStay: '1 Year (Renewable annually)',
    taxRate: '5% – 15% Flat Substitute Tax (Regime Forfettario for freelancers)',
    isZeroTax: false,
    processingTime: '30 – 45 Days via Italian Consulates',
    cost: 116,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Proof of highly qualified remote work in tech, creative, consulting or executive fields',
      'Minimum €28,000 annual verified gross remote earnings',
      '6+ months prior remote work experience with non-Italian clients',
      'Italian Partita IVA or tax registration and local residential lease'
    ],
    popularHubs: ['Milan', 'Rome', 'Florence', 'Palermo (Sicily)', 'Bologna', 'Turin', 'Cagliari (Sardinia)'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-greece-dvn',
    country: 'Greece',
    countryCode: 'GR',
    flagEmoji: '🇬🇷',
    visaName: 'Greece Digital Nomad Visa (Law 4825/2021)',
    minMonthlyIncome: '€3,500 / month (+20% spouse, +15% child)',
    incomeThresholdUsd: 3800,
    durationStay: '1 Year Visa + 2-Year Renewable Residence Permit',
    taxRate: '50% Income Tax Exemption for 7 Years',
    isZeroTax: false,
    processingTime: '10 – 15 Business Days Fast-Track',
    cost: 75,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Proof of remote work for non-Greek entities or foreign clients',
      'Net monthly earnings certificate of at least €3,500/mo into bank account',
      'Greek AFM tax ID and certified health insurance policy (€30,000 minimum)',
      'Clean background check and valid international passport'
    ],
    popularHubs: ['Athens', 'Chania (Crete)', 'Thessaloniki', 'Rhodes', 'Santorini', 'Corfu'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-malta-nrp',
    country: 'Malta',
    countryCode: 'MT',
    flagEmoji: '🇲🇹',
    visaName: 'Malta Nomad Residence Permit (Residency Malta)',
    minMonthlyIncome: '€3,500 / month gross income',
    incomeThresholdUsd: 3800,
    durationStay: '1 Year (Renewable up to 4 Years total)',
    taxRate: '0% Local Income Tax on foreign earnings (10% flat optional nomad tax)',
    isZeroTax: true,
    processingTime: '30 – 45 Days Online via Residency Malta Agency',
    cost: 300,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Work contract with an overseas employer OR Proof of freelance client agreements',
      '300+ Mbps nationwide 5G/fiber coverage across Malta and Gozo',
      'Valid international health insurance covering full hospitalisation in Malta',
      'Rental lease agreement in Malta/Gozo for duration of stay'
    ],
    popularHubs: ['Valletta', 'Sliema', 'St. Julian\'s', 'Victoria (Gozo Island)', 'Gzira'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-croatia-dtr',
    country: 'Croatia',
    countryCode: 'HR',
    flagEmoji: '🇭🇷',
    visaName: 'Croatia Digital Nomad Temporary Stay Permit',
    minMonthlyIncome: '€2,540 / month (~€30,500 in bank deposit)',
    incomeThresholdUsd: 2750,
    durationStay: '1 Year (Can re-apply after 6-month cooling period)',
    taxRate: '100% Tax Exemption (0% local income tax on all remote work earnings)',
    isZeroTax: true,
    processingTime: '15 – 25 Business Days via MUP Portal',
    cost: 150,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Provide services through communication tech to non-Croatian employers',
      'Bank statement verifying incoming €2,540/mo or €30,500 total deposit',
      'Croatian OIB tax identification number and registered rental contract',
      'Comprehensive private health insurance and apostilled criminal record'
    ],
    popularHubs: ['Split', 'Zagreb', 'Dubrovnik', 'Zadar', 'Rijeka', 'Hvar Island'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-cyprus-dvn',
    country: 'Cyprus',
    countryCode: 'CY',
    flagEmoji: '🇨🇾',
    visaName: 'Cyprus Digital Nomad Visa Scheme',
    minMonthlyIncome: '€3,500 / month net income',
    incomeThresholdUsd: 3800,
    durationStay: '1 Year (Renewable for 2 additional years)',
    taxRate: '0% Tax for non-tax residents (<183 days) / 60-Day Non-Dom Tax Haven',
    isZeroTax: true,
    processingTime: '5 – 7 Weeks via Migration Department',
    cost: 70,
    schengenStatus: 'Non-Schengen Europe',
    region: 'Europe',
    keyRequirements: [
      'Employment contract with companies outside Cyprus',
      'Net monthly remote earnings proof of €3,500/mo (+20% spouse, +15% child)',
      'Cyprus residential rental agreement and title deed copy',
      'Clean police record and medical insurance with €30,000 coverage'
    ],
    popularHubs: ['Limassol', 'Paphos', 'Larnaca', 'Nicosia', 'Ayia Napa'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-estonia-dvn',
    country: 'Estonia',
    countryCode: 'EE',
    flagEmoji: '🇪🇪',
    visaName: 'Estonia Digital Nomad Visa & e-Residency',
    minMonthlyIncome: '€4,500 / month gross (6-month pre-tax average)',
    incomeThresholdUsd: 4850,
    durationStay: '1 Year Long-Stay (Type D) Visa',
    taxRate: '0% Tax for stays under 183 days (0% Corporate Tax on reinvested profits)',
    isZeroTax: false,
    processingTime: '15 – 30 Days via Estonian Police and Border Guard',
    cost: 100,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Perform work duties remotely using telecommunications technologies',
      'Active employment contract or freelance business registered abroad',
      'Gross monthly income of €4,500 for the last 6 consecutive months',
      'Estonian e-Residency digital ID card integration available'
    ],
    popularHubs: ['Tallinn (Telliskivi)', 'Tartu', 'Pärnu'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-hungary-whitecard',
    country: 'Hungary',
    countryCode: 'HU',
    flagEmoji: '🇭🇺',
    visaName: 'Hungary White Card (Nomad Residence Permit)',
    minMonthlyIncome: '€3,000 / month (for the preceding 6 months)',
    incomeThresholdUsd: 3250,
    durationStay: '1 Year (Renewable for 1 additional year)',
    taxRate: '0% Hungarian Tax for first 183 days / 15% Flat Personal Rate',
    isZeroTax: false,
    processingTime: '21 – 30 Days via National Directorate-General for Aliens Policing',
    cost: 110,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Proof of verified employment contract outside Hungary or overseas company ownership',
      'Average bank balance showing steady €3,000/mo income for 6 months',
      'Valid Budapest lease agreement and health insurance coverage',
      'Clean police clearance certificate'
    ],
    popularHubs: ['Budapest (District VII & V)', 'Debrecen', 'Szeged', 'Lake Balaton'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-germany-freelance',
    country: 'Germany',
    countryCode: 'DE',
    flagEmoji: '🇩🇪',
    visaName: 'Germany Freelance & Remote Specialist Visa (Freiberufler)',
    minMonthlyIncome: '€2,500 / month + Proof of Self-Sufficiency',
    incomeThresholdUsd: 2700,
    durationStay: '1 to 3 Years (Path to German Permanent Settlement PR)',
    taxRate: 'Progressive German Income Tax with high business expense deductibility',
    isZeroTax: false,
    processingTime: '4 – 8 Weeks via Ausländerbehörde',
    cost: 100,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Letters of intent or freelance contracts from international and German clients',
      'Professional portfolio, CV, and university credentials',
      'Comprehensive German statutory or private health insurance policy',
      'Adequate retirement pension provision if age 45+'
    ],
    popularHubs: ['Berlin (Kreuzberg/Mitte)', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-czech-zivno',
    country: 'Czech Republic (Czechia)',
    countryCode: 'CZ',
    flagEmoji: '🇨🇿',
    visaName: 'Czechia Zivno Freelance Long-Stay Visa',
    minMonthlyIncome: '~$6,000 in bank deposit account (~150,000 CZK)',
    incomeThresholdUsd: 2200,
    durationStay: '1 Year (Renewable for 2-year increments)',
    taxRate: 'Low Pausální Dan (Lump-sum flat tax of ~€300/mo including health & pension)',
    isZeroTax: false,
    processingTime: '60 – 90 Days via Czech Embassy',
    cost: 200,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Zivnostensky List (Czech Trade License registration)',
      'Proof of funds: Bank statement showing minimum $6,000 USD balance',
      'Proof of registered accommodation in Prague or Czech cities for 12 months',
      'Comprehensive complex medical travel insurance (PVZP or equivalent)'
    ],
    popularHubs: ['Prague (Vinohrady/Zizkov)', 'Brno', 'Olomouc', 'Cesky Krumlov'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-bulgaria-nomad',
    country: 'Bulgaria',
    countryCode: 'BG',
    flagEmoji: '🇧🇬',
    visaName: 'Bulgaria 10% Flat Tax Nomad Residency Hub',
    minMonthlyIncome: '€1,500 / month (Low living cost & 10% flat EU tax rate)',
    incomeThresholdUsd: 1600,
    durationStay: '1 Year Renewable D-Visa & Residence Card',
    taxRate: '10% Flat Corporate & 10% Flat Personal Income Tax (Lowest in EU)',
    isZeroTax: false,
    processingTime: '15 – 30 Business Days',
    cost: 110,
    schengenStatus: 'Full Schengen Zone',
    region: 'Europe',
    keyRequirements: [
      'Remote employment or freelance contracts with international clients',
      'Bank statement showing incoming funds and €1,500/mo sufficiency',
      'Bulgarian address registration and local health insurance',
      'World-renowned Bansko Mountain Coworking Hub network integration'
    ],
    popularHubs: ['Bansko (Alpine Coworking Hub)', 'Sofia', 'Plovdiv', 'Varna (Black Sea Coast)'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-montenegro-nomad',
    country: 'Montenegro',
    countryCode: 'ME',
    flagEmoji: '🇲🇪',
    visaName: 'Montenegro Digital Nomad Visa (Program 2026)',
    minMonthlyIncome: '€1,400 / month (2x Montenegro Average Wage)',
    incomeThresholdUsd: 1500,
    durationStay: '2 Years (Renewable for an additional 2 Years)',
    taxRate: '0% Income Tax on foreign remote earnings • 9% Flat Business Tax',
    isZeroTax: true,
    processingTime: '20 – 30 Business Days via Ministry of Interior',
    cost: 67,
    schengenStatus: 'Non-Schengen Europe',
    region: 'Europe',
    keyRequirements: [
      'Proof of remote work for foreign companies or independent freelance contracts',
      'Monthly earnings of at least €1,400 into international account',
      'Registered rental contract in Bay of Kotor, Budva, or Podgorica',
      'Clean background check and international health insurance'
    ],
    popularHubs: ['Kotor Bay', 'Tivat (Porto Montenegro)', 'Budva', 'Podgorica', 'Herceg Novi'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-albania-unique',
    country: 'Albania',
    countryCode: 'AL',
    flagEmoji: '🇦🇱',
    visaName: 'Albania Digital Nomad Unique Permit (Leje Unike)',
    minMonthlyIncome: '€1,200 / month ($1,300/mo income or $12k savings)',
    incomeThresholdUsd: 1300,
    durationStay: '1 Year (Renewable up to 5 Years) ➔ Permanent Residence',
    taxRate: '0% Personal Income Tax for first 12 months for digital nomads',
    isZeroTax: true,
    processingTime: '10 – 15 Business Days Online via e-Albania Portal',
    cost: 50,
    schengenStatus: 'Non-Schengen Europe',
    region: 'Europe',
    keyRequirements: [
      'Proof of remote employment contract or service agreements outside Albania',
      'Bank statement showing incoming monthly income of at least €1,200',
      'Rental agreement in Tirana or Albanian Riviera coastal towns',
      'Clean police certificate and private health insurance policy'
    ],
    popularHubs: ['Tirana (Blloku)', 'Sarandë (Riviera)', 'Vlorë', 'Durrës', 'Shkodër'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-georgia-remotely',
    country: 'Georgia',
    countryCode: 'GE',
    flagEmoji: '🇬🇪',
    visaName: 'Remotely From Georgia & 1% Individual Entrepreneur Scheme',
    minMonthlyIncome: '$2,000 / month ($24,000 annual income)',
    incomeThresholdUsd: 2000,
    durationStay: '365 Days Visa-Free for 95+ nationalities (Renewable by border run)',
    taxRate: '1% Flat Small Business Tax (Up to ~$180,000 USD gross annual turnover)',
    isZeroTax: false,
    processingTime: '5 – 8 Business Days Instant Registration',
    cost: 0,
    schengenStatus: 'Non-Schengen Europe',
    region: 'Europe',
    keyRequirements: [
      'Remote worker, freelancer, or sole proprietor with non-Georgian clientele',
      'Georgian Individual Entrepreneur (IE) & Small Business Status registration',
      'Bank of Georgia or TBC Bank multi-currency account setup',
      'Valid passport and international travel health insurance'
    ],
    popularHubs: ['Tbilisi (Fabrika/Vake)', 'Batumi (Black Sea)', 'Kutaisi'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-japan-dvn',
    country: 'Japan',
    countryCode: 'JP',
    flagEmoji: '🇯🇵',
    visaName: 'Japan Digital Nomad Visa (Specified Activities Remote Work)',
    minMonthlyIncome: '¥10,000,000 / year (~$65,000 USD annual income)',
    incomeThresholdUsd: 5400,
    durationStay: '6 Months (Can re-apply after 6-month period abroad)',
    taxRate: '0% Japanese Income Tax (Exempt from local resident taxes & social contributions)',
    isZeroTax: true,
    processingTime: '2 – 4 Weeks via Japanese Embassies & Consulates',
    cost: 25,
    schengenStatus: 'Asia-Pacific',
    region: 'Asia-Pacific',
    keyRequirements: [
      'Citizen of 49 visa-exempt countries/regions with bilateral tax treaties (US, UK, EU, etc.)',
      'Verified annual earnings exceeding ¥10 million JPY (~$65k USD)',
      'Private medical insurance with death/injury/hospital coverage of at least ¥10M JPY',
      'Allows spouse and accompanying dependent children'
    ],
    popularHubs: ['Tokyo (Shibuya/Shinjuku)', 'Kyoto', 'Fukuoka (Startup City)', 'Osaka', 'Sapporo'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-southkorea-workation',
    country: 'South Korea',
    countryCode: 'KR',
    flagEmoji: '🇰🇷',
    visaName: 'South Korea Workation Visa (F-1-D)',
    minMonthlyIncome: '~$66,000 / year (2x Korean Gross National Income per capita)',
    incomeThresholdUsd: 5500,
    durationStay: '1 Year (Extendable for 1 additional year, 2 years total)',
    taxRate: '0% Korean Domestic Tax on overseas employer earnings',
    isZeroTax: true,
    processingTime: '10 – 14 Business Days via Korean Diplomatic Missions',
    cost: 60,
    schengenStatus: 'Asia-Pacific',
    region: 'Asia-Pacific',
    keyRequirements: [
      'Employed by a foreign company for at least 1 year in the same industry',
      'Income equal to 2x Korea GNI (~85M KRW / ~$66k USD) verified by tax returns',
      'Personal medical insurance covering minimum 100M KRW (~$75k USD)',
      'Clean criminal history record check'
    ],
    popularHubs: ['Seoul (Gangnam/Hongdae)', 'Busan (Haeundae Beach)', 'Jeju Island (Nomad Workation)'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-thailand-dtv',
    country: 'Thailand',
    countryCode: 'TH',
    flagEmoji: '🇹🇭',
    visaName: 'Destination Thailand Visa (DTV 5-Year Nomad Visa)',
    minMonthlyIncome: '500,000 THB (~$14,000 USD) Proof of Funds in Bank',
    incomeThresholdUsd: 1200,
    durationStay: '5 Years Multiple Entry (180 Days per stay, extendable by 180 days in-country)',
    taxRate: '0% Tax on foreign income not remitted to Thailand in the same tax year',
    isZeroTax: true,
    processingTime: '5 – 10 Business Days via Thai Official E-Visa Portal',
    cost: 300,
    schengenStatus: 'Asia-Pacific',
    region: 'Asia-Pacific',
    keyRequirements: [
      'Employment contract, remote company portfolio, or professional digital nomad status',
      'Financial proof: Bank statement showing minimum 500,000 THB (~$14,000 USD) balance',
      'Valid passport with at least 6 months validity',
      'Includes spouse and dependent children under 20 years old'
    ],
    popularHubs: ['Chiang Mai (Nimman/Old City)', 'Bangkok (Sukhumvit/Thonglor)', 'Koh Phangan', 'Phuket (Rawai/Bang Tao)', 'Koh Samui'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-bali-indonesia',
    country: 'Indonesia (Bali)',
    countryCode: 'ID',
    flagEmoji: '🇮🇩',
    visaName: 'Indonesia E33G Remote Worker / Digital Nomad Visa',
    minMonthlyIncome: '$60,000 / year (~$5,000/mo) verified salary or contract',
    incomeThresholdUsd: 5000,
    durationStay: '1 Year (Renewable up to 2 Years without leaving Indonesia)',
    taxRate: '0% Indonesian Income Tax (Exempt from local tax on foreign-sourced earnings)',
    isZeroTax: true,
    processingTime: '5 – 8 Business Days Online E-Visa Instant Processing',
    cost: 350,
    schengenStatus: 'Asia-Pacific',
    region: 'Asia-Pacific',
    keyRequirements: [
      'Proof of employment contract from an overseas company outside Indonesia',
      'Annual earnings proof of at least $60,000 USD (Salary slips or tax statements)',
      'Bank statement showing minimum $2,000 USD balance for living expenses',
      'Valid passport with at least 6 months validity'
    ],
    popularHubs: ['Canggu (Echo Beach)', 'Ubud', 'Pererenan', 'Uluwatu', 'Seminyak', 'Sanur', 'Lombok'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-philippines-nomad',
    country: 'Philippines',
    countryCode: 'PH',
    flagEmoji: '🇵🇭',
    visaName: 'Philippines Digital Nomad Visa & Special Resident Stream',
    minMonthlyIncome: '$1,500 / month ($18,000 annual remote income)',
    incomeThresholdUsd: 1500,
    durationStay: '1 Year (Renewable for an additional 12 Months)',
    taxRate: '0% Philippine Income Tax on foreign remote service earnings',
    isZeroTax: true,
    processingTime: '10 – 15 Business Days via Bureau of Immigration',
    cost: 180,
    schengenStatus: 'Asia-Pacific',
    region: 'Asia-Pacific',
    keyRequirements: [
      'Active remote work contract with foreign employer or independent overseas clientele',
      'Bank statements verifying consistent monthly income of at least $1,500 USD',
      'Clean background check and international travel health insurance',
      'Fast high-speed fiber hubs in Davao City, BGC Manila, Cebu, and Siargao Island'
    ],
    popularHubs: ['Davao City (Abreeza/Lanang)', 'Manila (BGC Taguig/Makati)', 'Cebu IT Park', 'Siargao Island (Cloud 9)', 'Boracay', 'La Union'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-malaysia-derantau',
    country: 'Malaysia',
    countryCode: 'MY',
    flagEmoji: '🇲🇾',
    visaName: 'Malaysia DE Rantau Nomad Pass (MDEC)',
    minMonthlyIncome: '$24,000 / year (~$2,000/mo) for Tech & Digital Professionals',
    incomeThresholdUsd: 2000,
    durationStay: '12 Months (Renewable for an additional 12 Months)',
    taxRate: '0% Tax on foreign-sourced earnings remitted to Malaysia',
    isZeroTax: true,
    processingTime: '4 – 6 Weeks via MDEC Online Portal',
    cost: 220,
    schengenStatus: 'Asia-Pacific',
    region: 'Asia-Pacific',
    keyRequirements: [
      'Digital professional in software, IT, digital marketing, AI, creative content, or consulting',
      'Proof of active employment contract or multiple freelance project invoices',
      'Bank statements showing last 3 months salary deposits meeting $24k/yr',
      'Certified DE Rantau Coworking & Coliving Partner Hub network access'
    ],
    popularHubs: ['Kuala Lumpur (KLCC/Bangsar)', 'Penang (George Town)', 'Langkawi Island', 'Johor Bahru'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-taiwan-goldcard',
    country: 'Taiwan',
    countryCode: 'TW',
    flagEmoji: '🇹🇼',
    visaName: 'Taiwan Employment Gold Card (4-in-1 Remote Visa)',
    minMonthlyIncome: 'NT$160,000 / month (~$5,000 USD/mo) in tech/science/finance',
    incomeThresholdUsd: 5000,
    durationStay: '1 to 3 Years (Open work permit & unlimited re-entry)',
    taxRate: '50% Income Tax Exemption on annual salary above NT$3M for 5 years',
    isZeroTax: false,
    processingTime: '30 – 45 Days Online via National Immigration Agency',
    cost: 200,
    schengenStatus: 'Asia-Pacific',
    region: 'Asia-Pacific',
    keyRequirements: [
      'Proven expertise in Science & Tech, Economy, Education, Culture/Arts, Finance, or Law',
      'Tax statement or salary slips proving monthly earnings of NT$160,000+ (~$5k USD)',
      'Includes open residency, National Health Insurance (NHI) eligibility after 6 months',
      'Fast-track permanent residency pathway (3 years for Gold Card holders)'
    ],
    popularHubs: ['Taipei (Daan/Xinyi)', 'Taichung', 'Kaohsiung', 'Hsinchu (Silicon Island)'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-srilanka-nomad',
    country: 'Sri Lanka',
    countryCode: 'LK',
    flagEmoji: '🇱🇰',
    visaName: 'Sri Lanka Digital Nomad Long Stay Visa',
    minMonthlyIncome: '$2,000 / month into a local or foreign bank account',
    incomeThresholdUsd: 2000,
    durationStay: '1 Year (Renewable annually)',
    taxRate: '0% Sri Lankan Income Tax on foreign remittances',
    isZeroTax: true,
    processingTime: '7 – 10 Business Days via ETA Portal',
    cost: 500,
    schengenStatus: 'Asia-Pacific',
    region: 'Asia-Pacific',
    keyRequirements: [
      'Proof of overseas remote employment or digital freelance business ownership',
      'Monthly income proof of $2,000 for individual ($3,000 for family)',
      'Valid passport with at least 6 months validity',
      'Popular beach surf and mountain coworking hubs'
    ],
    popularHubs: ['Ahangama (Surf Coworking)', 'Weligama', 'Colombo', 'Hiriketiya', 'Ella (Hill Country)'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-costarica-rentista',
    country: 'Costa Rica',
    countryCode: 'CR',
    flagEmoji: '🇨🇷',
    visaName: 'Costa Rica Estancia Remote Worker Visa (Law 9996)',
    minMonthlyIncome: '$3,000 / month ($4,000 for family)',
    incomeThresholdUsd: 3000,
    durationStay: '1 Year (Renewable for an additional year)',
    taxRate: '100% Tax Exemption (0% local tax on foreign income, import duty waiver on equipment)',
    isZeroTax: true,
    processingTime: '14 – 21 Business Days via DGME',
    cost: 250,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Bank statements certified showing regular $3,000/mo incoming remote salary',
      'Medical insurance policy covering minimum $50,000 USD in Costa Rica',
      'Police background check and passport copy',
      'Driver’s license validation for immediate local driving privileges'
    ],
    popularHubs: ['Santa Teresa', 'Nosara', 'Puerto Viejo', 'San José (Escazú)', 'Tamarindo', 'Manuel Antonio'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-mexico-resident',
    country: 'Mexico',
    countryCode: 'MX',
    flagEmoji: '🇲🇽',
    visaName: 'Mexico Residente Temporal (Remote Worker Stream)',
    minMonthlyIncome: '~$3,500 – $4,300 / month net income or $70k in savings',
    incomeThresholdUsd: 3800,
    durationStay: '1 to 4 Years (Path to Mexican Permanent Residency & Citizenship)',
    taxRate: '0% Mexican Tax on foreign-sourced earnings not paid by Mexican legal entities',
    isZeroTax: true,
    processingTime: '1 – 2 Weeks at Mexican Consulates Abroad',
    cost: 250,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Last 6 months of bank statements proving steady remote income of ~$3,800/mo',
      'OR Last 12 months of investment/savings accounts showing $70,000+ balance',
      'Valid passport and consular appointment interview',
      'Can exchange visa sticker for Residente Temporal plastic card at INM within 30 days'
    ],
    popularHubs: ['Mexico City (Condesa/Roma)', 'Playa del Carmen', 'Puerto Escondido', 'Oaxaca', 'Tulum', 'Guadalajara'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-colombia-nomad',
    country: 'Colombia',
    countryCode: 'CO',
    flagEmoji: '🇨🇴',
    visaName: 'Colombia Visa V Nómadas Digitales (Resolution 5477)',
    minMonthlyIncome: '~$1,400 / month (3x Colombian Minimum Wage)',
    incomeThresholdUsd: 1400,
    durationStay: 'Up to 2 Years (Allows multiple entries and 180 days stay per calendar year)',
    taxRate: '0% Tax for stays under 183 days per 365-day rolling period',
    isZeroTax: true,
    processingTime: '15 – 30 Days Online via Cancillería Portal',
    cost: 230,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Letter in Spanish from foreign employer stating remote role and salary',
      'Bank statements from last 3 months demonstrating minimum $1,400/mo income',
      'International health insurance policy covering Colombia for full validity',
      'Valid passport with at least 2 blank pages'
    ],
    popularHubs: ['Medellín (El Poblado/Laureles)', 'Bogotá (Chapinero/Usaquén)', 'Cartagena', 'Santa Marta', 'Cali'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-brazil-vitemxiv',
    country: 'Brazil',
    countryCode: 'BR',
    flagEmoji: '🇧🇷',
    visaName: 'Brazil VITEM XIV Digital Nomad Visa (CNIG Res. 45)',
    minMonthlyIncome: '$1,500 / month OR $18,000 available bank balance',
    incomeThresholdUsd: 1500,
    durationStay: '1 Year (Renewable for an additional 1 Year in-country)',
    taxRate: '0% Tax for first 183 days / Tiered progressive rate after tax residency triggered',
    isZeroTax: true,
    processingTime: '15 – 25 Business Days via e-Consular Portal',
    cost: 160,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Employment contract with non-Brazilian company or freelance client agreements',
      'Bank statements showing $1,500/mo monthly inflow OR $18,000 USD lump sum proof',
      'Clean criminal record certificate issued within the last 90 days',
      'Health insurance valid throughout Brazil (minimum $30,000 coverage)'
    ],
    popularHubs: ['Florianópolis (Magic Island)', 'Rio de Janeiro (Ipanema/Leblon)', 'São Paulo (Vila Madalena)', 'Pipa', 'Salvador'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-argentina-nomad',
    country: 'Argentina',
    countryCode: 'AR',
    flagEmoji: '🇦🇷',
    visaName: 'Argentina Digital Nomad Temporary Residency Permit',
    minMonthlyIncome: '$1,200 / month remote income',
    incomeThresholdUsd: 1200,
    durationStay: '180 Days (Renewable for an additional 180 Days)',
    taxRate: '0% Argentine Tax on foreign earnings • Official MEP currency exchange rate benefits',
    isZeroTax: true,
    processingTime: '10 – 20 Business Days via Migraciones Online',
    cost: 120,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Resume/CV and proof of remote employment or freelance client contracts',
      'Bank statement showing regular monthly remuneration of at least $1,200 USD',
      'Valid passport copy and digital photograph',
      'Special discounts on Aerolineas Argentinas and partner coworking hubs'
    ],
    popularHubs: ['Buenos Aires (Palermo Soho/Hollywood)', 'Mendoza (Wine Country)', 'Bariloche (Patagonia)', 'Córdoba'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-panama-nomad',
    country: 'Panama',
    countryCode: 'PA',
    flagEmoji: '🇵🇦',
    visaName: 'Panama Short Stay Remote Worker Visa (Visa de Corta Estancia)',
    minMonthlyIncome: '$3,000 / month ($4,000 for family)',
    incomeThresholdUsd: 3000,
    durationStay: '9 Months (Renewable for an additional 9 Months)',
    taxRate: '0% Panamanian Tax (Territorial tax system: 100% tax exempt on foreign income)',
    isZeroTax: true,
    processingTime: '20 – 30 Business Days via National Migration Service',
    cost: 300,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Employment contract with foreign corporation or proof of offshore freelance clients',
      'Bank statement or certified letter proving $3,000/mo income from foreign sources',
      'Panama health insurance policy with full hospitalisation coverage',
      'Clean background check and sworn affidavit of no local Panamanian employment'
    ],
    popularHubs: ['Panama City (Casco Viejo/Costa del Este)', 'Bocas del Toro (Surf Island)', 'Boquete (Highlands)', 'Playa Venao'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-uruguay-nomad',
    country: 'Uruguay',
    countryCode: 'UY',
    flagEmoji: '🇺🇾',
    visaName: 'Uruguay Digital Nomad Provisional Identity Permit',
    minMonthlyIncome: 'Self-sufficient income verification (~$1,500/mo)',
    incomeThresholdUsd: 1500,
    durationStay: '6 Months to 1 Year (Path to Uruguayan Legal Residency)',
    taxRate: '0% Tax on offshore income (10-year foreign tax holiday for new tax residents)',
    isZeroTax: true,
    processingTime: '5 – 10 Business Days via Online Ministry of Interior',
    cost: 40,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Affidavit of remote work capability and freelance services for companies outside Uruguay',
      'Clean police record from home country or residence',
      'Vaccination record and medical certificate',
      'High-speed fiber connectivity and safest country ranking in South America'
    ],
    popularHubs: ['Montevideo (Pocitos/Punta Carretas)', 'Punta del Este', 'Colonia del Sacramento', 'La Paloma'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-barbados-stamp',
    country: 'Barbados',
    countryCode: 'BB',
    flagEmoji: '🇧🇧',
    visaName: 'Barbados Welcome Stamp 12-Month Remote Work Visa',
    minMonthlyIncome: '$50,000 / year (~$4,166/mo) individual income',
    incomeThresholdUsd: 4166,
    durationStay: '12 Months (Renewable for consecutive 12-month periods)',
    taxRate: '0% Barbados Income Tax (Exempt from local personal and withholding taxes)',
    isZeroTax: true,
    processingTime: '5 – 7 Business Days Fast Online Approval',
    cost: 2000,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Annual earnings expectation of at least $50,000 USD over the 12-month stay',
      'Passport bio-data page and birth certificate copies',
      'Proof of relationship for accompanying family members ($3,000 family fee)',
      'World-class Caribbean beachfront workspaces and reliable fiber internet'
    ],
    popularHubs: ['Bridgetown', 'Holetown (West Coast Platinum Coast)', 'Christ Church (South Coast)', 'Bathsheba'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-bahamas-beats',
    country: 'Bahamas',
    countryCode: 'BS',
    flagEmoji: '🇧🇸',
    visaName: 'Bahamas BEATS (Extended Access Travel Stay)',
    minMonthlyIncome: 'Proof of Employment or Self-Employed Remote Business',
    incomeThresholdUsd: 2500,
    durationStay: '1 Year (Renewable up to 3 Years)',
    taxRate: '0% Personal Income Tax • 0% Corporate Tax • 0% Capital Gains Tax',
    isZeroTax: true,
    processingTime: '5 Business Days Electronic Authorization',
    cost: 1025,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Employment contract or business ownership certificate outside the Bahamas',
      'Valid passport copy and medical insurance coverage in Bahamas',
      'Student remote study stream also available for accredited universities',
      'Permits inter-island island hopping across 700+ islands and cays'
    ],
    popularHubs: ['Nassau (Paradise Island)', 'Freeport (Grand Bahama)', 'Eleuthera', 'Exuma'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-bermuda-work',
    country: 'Bermuda',
    countryCode: 'BM',
    flagEmoji: '🇧🇲',
    visaName: 'Work From Bermuda 1-Year Residential Certificate',
    minMonthlyIncome: 'Continuous source of remote income or substantial assets',
    incomeThresholdUsd: 4000,
    durationStay: '1 Year (Renewable on application)',
    taxRate: '0% Income Tax • 0% Capital Gains • Zero Tax Haven Jurisdiction',
    isZeroTax: true,
    processingTime: '5 – 7 Business Days',
    cost: 275,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Employed by a legitimate foreign company or operating an independent remote business',
      'Substantial financial means to support residency in Bermuda',
      'Health insurance policy valid in Bermuda and clean background check',
      'Direct flights from New York (2 hrs), London, Miami, and Toronto'
    ],
    popularHubs: ['Hamilton', 'St. George\'s', 'Paget', 'Pembroke'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-cayman-citizen',
    country: 'Cayman Islands',
    countryCode: 'KY',
    flagEmoji: '🇰🇾',
    visaName: 'Global Citizen Concierge Program (GCCP)',
    minMonthlyIncome: '$100,000 / year ($150,000 with spouse/partner)',
    incomeThresholdUsd: 8333,
    durationStay: '2 Years Luxury Caribbean Stay',
    taxRate: '0% Income Tax • 0% Direct Tax • Premier Sovereign Offshore Wealth Center',
    isZeroTax: true,
    processingTime: '15 – 20 Business Days',
    cost: 1463,
    schengenStatus: 'Americas / Caribbean',
    region: 'Latin America & Caribbean',
    keyRequirements: [
      'Letter of employment showing minimum $100,000 USD annual salary from overseas firm',
      'Bank reference letter from top-tier international banking institution',
      'Police clearance and comprehensive international medical insurance',
      'Dedicated ATLAS VIP Private Banker and Concierge on-boarding'
    ],
    popularHubs: ['Seven Mile Beach (Grand Cayman)', 'George Town', 'Cayman Brac'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-uae-dubai',
    country: 'United Arab Emirates (Dubai)',
    countryCode: 'AE',
    flagEmoji: '🇦🇪',
    visaName: 'Dubai Virtual Working Programme (1-Year Nomad Residency)',
    minMonthlyIncome: '$3,500 / month salary or equivalent company income',
    incomeThresholdUsd: 3500,
    durationStay: '1 Year (Renewable indefinitely with Emirates ID card)',
    taxRate: '0% Personal Income Tax • 0% Capital Gains Tax • 0% Inheritance Tax',
    isZeroTax: true,
    processingTime: '5 – 7 Business Days Instant E-Visa',
    cost: 287,
    schengenStatus: 'Middle East 0% Tax',
    region: 'Middle East & Africa',
    keyRequirements: [
      'Proof of Employment with 1-year contract validity OR Proof of Company Ownership',
      'Last 3 months of bank statements showing regular salary deposits',
      'Valid health insurance with UAE medical coverage',
      'Passport valid for at least 6 months with Emirates ID biometric issuance'
    ],
    popularHubs: ['Dubai Marina', 'Downtown Dubai', 'Jumeirah Lakes Towers (JLT)', 'DIFC', 'Palm Jumeirah', 'Abu Dhabi Yas Island'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-mauritius-premium',
    country: 'Mauritius',
    countryCode: 'MU',
    flagEmoji: '🇲🇺',
    visaName: 'Mauritius Premium Visa (Long-Stay Remote Visa)',
    minMonthlyIncome: '$1,500 / month ($500 per dependent child)',
    incomeThresholdUsd: 1500,
    durationStay: '1 Year (Free government application, renewable indefinitely)',
    taxRate: '0% Mauritian Tax on money spent locally using foreign cards / 15% flat if remitted',
    isZeroTax: true,
    processingTime: '48 – 72 Hours Fast Online Approval',
    cost: 0,
    schengenStatus: 'Middle East 0% Tax',
    region: 'Middle East & Africa',
    keyRequirements: [
      'Proof of long stay intent, remote employment, or freelance business abroad',
      'Bank statement showing incoming monthly transfer of at least $1,500 USD',
      'Travel and health insurance covering full duration of stay in Mauritius',
      'Confirmed return flight ticket and local accommodation booking'
    ],
    popularHubs: ['Grand Baie', 'Tamarin (West Coast Surf & Cowork)', 'Flic-en-Flac', 'Port Louis', 'Le Morne'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-southafrica-nomad',
    country: 'South Africa',
    countryCode: 'ZA',
    flagEmoji: '🇿🇦',
    visaName: 'South Africa Remote Working Visa',
    minMonthlyIncome: 'R650,796 / year (~$35,000 USD / ~$3,000/mo)',
    incomeThresholdUsd: 3000,
    durationStay: '1 to 3 Years Multi-Entry',
    taxRate: '0% South African Tax for stays up to 6 months per 12-month period',
    isZeroTax: true,
    processingTime: '20 – 30 Business Days via VFS Global & DHA',
    cost: 180,
    schengenStatus: 'Middle East 0% Tax',
    region: 'Middle East & Africa',
    keyRequirements: [
      'Gross annual income of at least R650,796 (~$35,000 USD) from overseas employment',
      'Employment contract with foreign company outside South Africa',
      'Registered residential lease in Cape Town, Johannesburg or Garden Route',
      'Medical insurance coverage and police clearance certificate'
    ],
    popularHubs: ['Cape Town (Camps Bay/Sea Point/Kloof St)', 'Johannesburg (Rosebank)', 'Stellenbosch (Winelands)', 'Knysna'],
    fastTrackFilingAvailable: true,
  },
  {
    id: 'visa-capeverde-nomad',
    country: 'Cape Verde (Cabo Verde)',
    countryCode: 'CV',
    flagEmoji: '🇨🇻',
    visaName: 'Cabo Verde Remote Working Program',
    minMonthlyIncome: '€1,500 / month individual (€2,700 for family)',
    incomeThresholdUsd: 1600,
    durationStay: '6 Months (Renewable for an additional 6 Months)',
    taxRate: '0% Local Income Tax for remote workers',
    isZeroTax: true,
    processingTime: '5 – 10 Business Days via Official E-Visa Portal',
    cost: 60,
    schengenStatus: 'Middle East 0% Tax',
    region: 'Middle East & Africa',
    keyRequirements: [
      'Passport bio-page and proof of remote employment or independent digital business',
      'Bank statement showing average monthly balance of €1,500 over last 6 months',
      'Health insurance and local hotel/coliving reservation confirmation',
      'Year-round tropical climate on Atlantic island archipelago'
    ],
    popularHubs: ['Santa Maria (Sal Island)', 'Mindelo (São Vicente)', 'Praia (Santiago)'],
    fastTrackFilingAvailable: true,
  }
];

export const MOCK_NOMAD_COLIVINGS: NomadColivingSpace[] = [
  {
    id: 'coliving-lisbon-cais',
    name: 'Outsite Coliving Lisbon & Ocean Workspace',
    city: 'Lisbon (Cais do Sodré)',
    country: 'Portugal',
    monthlyPublicRate: 2100,
    monthlyMemberRate: 1150,
    savingsPercentage: 45,
    wifiSpeedMbps: 500,
    roomType: 'Private Studio En-Suite',
    amenities: ['Dedicated Ergonomic Coworking Desk', '500 Mbps Redundant Fiber Wi-Fi', 'Weekly Community Dinners & Wine Tastings', 'Private En-Suite Bathroom & AC', 'Rooftop Workspace overlooking Tagus River'],
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  },
  {
    id: 'coliving-bali-canggu',
    name: 'Dojo & Outpost Nomad Resort Canggu',
    city: 'Bali (Canggu Beach)',
    country: 'Indonesia',
    monthlyPublicRate: 1650,
    monthlyMemberRate: 890,
    savingsPercentage: 46,
    wifiSpeedMbps: 300,
    roomType: 'Coliving Master Suite',
    amenities: ['Poolside Fiber Coworking Desks', 'Soundproof Zoom Call Booths', 'Complimentary Daily Yoga & Ice Bath', 'Daily Scooter Rental Discount', 'Air Conditioned Master Suite with Tropical Garden'],
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  },
  {
    id: 'coliving-chiangmai-alt',
    name: 'Alt_ChiangMai Luxury Coliving & Creator Space',
    city: 'Chiang Mai (Nimman)',
    country: 'Thailand',
    monthlyPublicRate: 1450,
    monthlyMemberRate: 750,
    savingsPercentage: 48,
    wifiSpeedMbps: 1000,
    roomType: 'Private Studio En-Suite',
    amenities: ['1 Gbps Fiber Dual-Line Redundancy', 'Podcast Studio & Ergonomic Herman Miller Chairs', 'Rooftop Cold Plunge & Sauna', 'Mastermind Brunches & Weekly Excursions', 'Daily Barista Craft Coffee Included'],
    image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  },
  {
    id: 'coliving-tokyo-roppongi',
    name: 'HafH & Roppongi Sky Coliving Residence',
    city: 'Tokyo (Roppongi/Minato)',
    country: 'Japan',
    monthlyPublicRate: 2800,
    monthlyMemberRate: 1550,
    savingsPercentage: 45,
    wifiSpeedMbps: 1000,
    roomType: 'Private Studio En-Suite',
    amenities: ['Ultra-High Speed Japanese 1 Gbps Fiber', 'Executive Work Lounge overlooking Tokyo Tower', 'Bilingual Concierge & Community Networking', 'Traditional Onsen Bathhouse Pass Included', 'Soundproof Call Pods & 4K Monitors'],
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  },
  {
    id: 'coliving-medellin-poblado',
    name: 'Selina Coworking & Rooftop Suites',
    city: 'Medellín (El Poblado)',
    country: 'Colombia',
    monthlyPublicRate: 1390,
    monthlyMemberRate: 740,
    savingsPercentage: 47,
    wifiSpeedMbps: 250,
    roomType: 'Private Studio En-Suite',
    amenities: ['24/7 Access Coworking Floor', 'Podcast Audio Recording Studio', 'Rooftop Bar with Salsa Nights', 'Private High-Floor Studio with Balcony View', 'Direct access to Parque Lleras cafes'],
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  },
  {
    id: 'coliving-barcelona-gracia',
    name: 'Sun and Co. Gràcia Design Villa',
    city: 'Barcelona (Gràcia)',
    country: 'Spain',
    monthlyPublicRate: 2350,
    monthlyMemberRate: 1290,
    savingsPercentage: 45,
    wifiSpeedMbps: 600,
    roomType: 'Private Studio En-Suite',
    amenities: ['Modernist Catalan High-Ceiling Studio', '600 Mbps Symmetric Fiber', 'Weekly Tapas Crawls & Networking', 'Private Sunny Terrace Workspaces', '24/7 Silent Work Library'],
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  },
  {
    id: 'coliving-cdmx-condesa',
    name: 'Casa Nomad Condesa Heritage Studios',
    city: 'Mexico City (Condesa)',
    country: 'Mexico',
    monthlyPublicRate: 1750,
    monthlyMemberRate: 920,
    savingsPercentage: 47,
    wifiSpeedMbps: 500,
    roomType: 'Private Studio En-Suite',
    amenities: ['Art Deco Historic Mansion Workspace', 'Rooftop Mezcal & Taco Community Evenings', '500 Mbps Backup Satellite Internet', 'Ergonomic Standing Desks', 'Steps from Parque México & Top Cafes'],
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  },
  {
    id: 'coliving-bansko-chalet',
    name: 'Coworking Bansko Mountain Alpine Hub',
    city: 'Bansko (Pirin Mountains)',
    country: 'Bulgaria (0% Non-Schengen Tax Haven)',
    monthlyPublicRate: 1050,
    monthlyMemberRate: 580,
    savingsPercentage: 45,
    wifiSpeedMbps: 1000,
    roomType: 'Coworking Villa Pod',
    amenities: ['1 Gbps Fiber High-Speed Internet', 'Ski-in / Coworking Lounge with Fireplace', 'Thermal Mineral Hot Springs Excursions', 'Bulgarian 10% Flat Tax Registration Concierge', 'Private Alpine Studio with Mountain View'],
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  },
  {
    id: 'coliving-capetown-camps',
    name: 'Atlantic Sea View Nomad Villa Camps Bay',
    city: 'Cape Town (Camps Bay)',
    country: 'South Africa',
    monthlyPublicRate: 2200,
    monthlyMemberRate: 1180,
    savingsPercentage: 46,
    wifiSpeedMbps: 500,
    roomType: 'Private Studio En-Suite',
    amenities: ['Uninterrupted Solar Inverter Power (0% Load Shedding)', 'Panoramic 12 Apostles & Ocean Views', 'Private Infinity Pool & Sunset BBQ Terrace', '500 Mbps Dedicated Business Fiber', 'Table Mountain Hiking Community Weekends'],
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    communityEventsIncluded: true,
  }
];

export const MOCK_VAULT_ACCOUNT: TravelVaultAccount = {
  userId: 'demo-vip-member-777',
  vaultUnits: 12450,
  tierMultiplier: 4,
  estimatedAnnualDividend: 384.20,
  totalLifetimeDividendsPaid: 290.00,
  nextPayoutDate: 'December 31, 2026',
  dividendHistory: [
    {
      year: 2025,
      amount: 290.00,
      destination: 'HotelsClub Visa Prepaid Card (•••• 8842)',
      paidAt: '2025-12-31 23:59 UTC'
    }
  ]
};

export const MOCK_VILLAS: LuxuryVillaEstate[] = [
  {
    id: 'villa-stbarts-etoile',
    name: 'Villa L’Étoile & Private Beach Estate',
    destination: 'St. Barts',
    region: 'Flamands Beach',
    country: 'Caribbean',
    bedrooms: 6,
    bathrooms: 7,
    maxGuests: 12,
    propertyType: 'Beachfront Villa',
    publicPricePerNight: 5800,
    memberPricePerNight: 3200,
    savingsPercentage: 45,
    amenities: ['Heated Infinity Pool overlooking Flamands Bay', 'Direct Private Beach Boardwalk', 'Outdoor Cinema & Teppanyaki Grill', 'State-of-the-art Gym & Spa', 'Air Conditioned Master Suites with Terrace'],
    staffIncluded: ['Private French Gourmet Chef', 'Full-Time Butler & Bartender', 'Daily Housekeeping & Turndown', 'Dedicated Airport Chauffeur'],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  }
];

export const MOCK_STATUS_MATCH_PROGRAMS: StatusMatchProgram[] = [
  {
    id: 'sm-hilton-diamond',
    loyaltyProgramName: 'Hilton Honors Diamond Tier',
    brand: 'Hilton Honors',
    matchedTier: 'Diamond VIP',
    minHotelsClubTier: 'gold',
    logo: '🏨',
    perks: [
      'Complimentary Room Upgrades to One-Bedroom Suites',
      'Executive Lounge Access with Free Breakfast & Evening Cocktails',
      'Daily $25 Food & Beverage Dining Credit per person',
      'Guaranteed 4:00 PM Late Check-out',
      '100% Bonus Points on all wholesale and direct stays'
    ],
    publicRequirement: 'Requires 60 Nights or $20,000 spend',
    matchProcessingTime: 'Instant / 12 Hours via API',
    statusValidity: 'Valid for 12 Full Months',
    applicationFee: 0,
    isComplimentaryForPlatinum: true,
  }
];

export const MOCK_FAST_TRACK_SERVICES: FastTrackAirportService[] = [
  {
    id: 'ft-lhr-vip',
    airportCode: 'LHR',
    airportName: 'London Heathrow International Airport',
    city: 'London',
    country: 'United Kingdom',
    serviceType: 'Arrival Jet Bridge Escort',
    provider: 'Diamond Air International',
    publicRetailPrice: 180,
    memberWholesalePrice: 85,
    savingsPercentage: 53,
    features: [
      'VIP Agent meets you directly at aircraft jet bridge with name board',
      'Diplomatic / Crew priority passport control lanes (3-minute clearance)',
      'Dedicated luggage porter to retrieve checked baggage',
      'Escort to your waiting chauffeur or Heathrow Express'
    ],
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    includesElectricBuggy: true,
    averageCustomsTimeMinutes: 3,
  }
];

export const MOCK_YACHTS: LuxuryYachtCharter[] = [
  {
    id: 'yacht-miami-sunseeker',
    name: '75ft Sunseeker Predator "Aura VIP"',
    lengthFeet: 75,
    builder: 'Sunseeker International',
    location: 'Miami Beach Marina, South Beach',
    city: 'Miami, FL',
    maxGuests: 12,
    staterooms: 3,
    crewCount: 2,
    includesCaptain: true,
    halfDayRetailPrice: 3800,
    halfDayMemberPrice: 2200,
    fullDayRetailPrice: 6500,
    fullDayMemberPrice: 3900,
    amenities: ['Licensed USCG Captain & First Mate', 'Open Bar with Top-Shelf Spirits', 'Full Sound System with Bluetooth', 'Air Conditioned Salon & Master Suite', 'Towel & Ice Service Included'],
    waterToys: ['2x Seabob Underwater Scooters', 'Inflatable Floating Island', 'Paddleboards & Snorkel Gear'],
    image: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d17?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  }
];

export const MOCK_SUPERCARS: SupercarRental[] = [
  {
    id: 'car-ferrari-f8',
    makeModel: 'Ferrari F8 Tributo (710 HP)',
    category: 'Supercar',
    city: 'Las Vegas, NV & Miami, FL',
    location: 'Hotel Doorstep VIP Delivery',
    horsepower: 710,
    zeroToSixtyMph: '2.9s',
    dailyRetailPrice: 1690,
    dailyMemberPrice: 950,
    includedMilesPerDay: 100,
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80',
    deliveryAvailable: true,
    features: ['Twin-Turbo 3.9L V8', 'Full Carbon Fiber Package', 'Exhaust Valve Switch', 'Free Concierge Hotel Delivery'],
  }
];

export const MOCK_PRICE_DROP_RECORDS: PriceDropRebookRecord[] = [
  {
    id: 'REBOOK-9824',
    userId: 'demo-vip-member-777',
    hotelName: 'The Grand Bellagio & Casino Resort',
    city: 'Las Vegas, NV',
    checkInDate: '2026-09-15',
    checkOutDate: '2026-09-18',
    nights: 3,
    originalPriceTotal: 594.00,
    newRebookedPriceTotal: 426.00,
    cashRefunded: 168.00,
    status: 'auto_rebooked_success',
    refundDestination: 'HotelsClub Visa Card',
    lastCheckedAt: '12 mins ago',
    rebookedAt: '2026-08-24 14:20 UTC',
    hotelImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
  }
];

export const MOCK_ACTIVE_GAP_ALERTS: TripGapAlert[] = [
  {
    id: 'gap-miami-cruise-flight',
    type: 'missing_flight',
    tripTitle: '7-Night Caribbean Cruise (Icon of the Seas)',
    destination: 'Miami, FL',
    dates: 'Oct 18 – Oct 25, 2026',
    message: 'You have booked your Caribbean cruise departing PortMiami on Oct 18, but you don\'t have a flight into Miami (MIA) or Fort Lauderdale (FLL) yet!',
    suggestedActionText: 'Find Wholesale Flights or Empty-Leg Jets to Miami',
    targetRoute: '/private-jets',
    category: 'jet'
  }
];

export const MOCK_PRIVATE_JETS: PrivateJetEmptyLeg[] = [
  {
    id: 'jet-opf-teb-300',
    aircraftType: 'Bombardier Challenger 300',
    category: 'Super Midsize',
    operator: 'VistaJet / XO Private Fleet',
    tailNumber: 'N882VJ',
    departureAirportCode: 'OPF',
    departureAirportName: 'Miami Opa-Locka Executive Airport',
    departureCity: 'Miami, FL',
    arrivalAirportCode: 'TEB',
    arrivalAirportName: 'Teterboro Executive Airport',
    arrivalCity: 'New York, NY',
    departureDate: '2026-09-12',
    departureTime: '14:30 EST',
    flightDuration: '2h 45m',
    maxPassengers: 8,
    wholeJetRetailPrice: 28500,
    wholeJetMemberPrice: 8900,
    perSeatMemberPrice: 1250,
    savingsPercentage: 69,
    amenities: ['Dom Pérignon Champagne & Full Bar', 'High-Speed Ka-Band Wi-Fi', 'Private Enclosed Lavatory', 'Pet Friendly In-Cabin', 'Direct Tarmac VIP Boarding'],
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'Atlantic Aviation FBO (No TSA Lines)',
    status: 'available'
  }
];

export const MOCK_FLIGHT_CLAIMS: FlightClaimRecord[] = [
  {
    id: 'CLM-AIR-9824',
    userId: 'demo-vip-member-777',
    flightNumber: 'LH442 (Lufthansa)',
    airline: 'Lufthansa',
    departureAirport: 'Frankfurt (FRA)',
    arrivalAirport: 'New York (JFK)',
    flightDate: '2026-08-15',
    delayHours: 4.5,
    claimReason: 'Flight Delayed 3+ Hours',
    estimatedPayout: 650.00,
    payoutCurrency: 'USD',
    passengerCount: 1,
    status: 'court_enforcement',
    airHelpReference: 'AH-EU261-8841920',
    payoutMethod: 'visa_card',
    createdAt: '2026-08-16',
  }
];

export const MOCK_INSURANCE_PLANS: TravelInsurancePlan[] = [
  {
    id: 'safetywing-nomad',
    title: 'Nomad Essential Travel Medical Protection',
    provider: 'SafetyWing',
    category: 'Nomad Essential Medical',
    dailyPrice: 1.60,
    annualPrice: 540,
    medicalEmergencyCoverage: '$250,000 Maximum',
    evacuationCoverage: '$100,000 Emergency Medical Evacuation',
    tripCancellationCoverage: '$5,000 Trip Interruption',
    lostLuggageCoverage: '$3,000 Checked Baggage Loss',
    deductible: '$0 Deductible',
    features: [
      'Covers 180+ countries worldwide',
      'Emergency room, ambulance & hospitalization',
      'Lost checked luggage & delayed flight assistance',
      'Instant digital insurance certificate for visa applications'
    ],
    instantPolicyPdf: true,
  }
];

export const PROVIDER_INSTRUCTION_GUIDES: ProviderInstructionGuide[] = [
  {
    id: 'sherpa-nomad-visas',
    providerName: 'Sherpa Travel / iVisa B2B API (Digital Nomad Visas)',
    category: 'Global Digital Nomad Visas & Schengen Rules Engine',
    estimatedApprovalTime: '1 – 2 Business Days',
    typicalCommissionOrSavings: 'Instant automated visa requirements & filing • $20 – $75 filing commission per approved visa (20%–30% rev-share)',
    portalUrl: 'https://www.ivisa.com/affiliates',
    requirements: [
      'B2B Travel Platform or VIP Nomad Membership Club Registration',
      'Passenger passport data & destination country forwarder'
    ],
    stepByStepGuide: [
      '1. Sign up for a partner affiliate account at ivisa.com/affiliates or joinsherpa.com/partners.',
      '2. In Developer Settings, copy your Affiliate Campaign ID and API Token.',
      '3. In HotelsClub Admin > Digital Nomad & Visas, paste your credentials and save.',
      '4. When a member applies for a Spain, Portugal, Dubai, or Thailand Nomad Visa, you earn $20–$75 per approved filing.'
    ]
  },
  {
    id: 'outsite-coliving-affiliate',
    providerName: 'Outsite & Selina Coliving Affiliate Network',
    category: 'Monthly Coliving Spaces & Long-Stays',
    estimatedApprovalTime: 'Instant / 1 Business Day',
    typicalCommissionOrSavings: '$50 – $100 per member signup • 8% – 10% commission on 30+ day monthly stays ($100–$250/mo)',
    portalUrl: 'https://www.outsite.co/affiliates',
    requirements: [
      'Travel platform, community, or nomad club website',
      'Payout details (PayPal / Bank Transfer)'
    ],
    stepByStepGuide: [
      '1. Register at outsite.co/affiliates and apply for Selina CoLive partner network.',
      '2. Copy your Outsite Affiliate Tracking Token.',
      '3. In HotelsClub Admin > Digital Nomad & Visas, paste your Outsite ID.',
      '4. When members book long-stay suites in Lisbon, Bali, or Medellín, your affiliate tracking is automatically attached.'
    ]
  },
  {
    id: 'wise-nomad-banking',
    providerName: 'Wise (TransferWise) & Remote Banking Affiliate',
    category: 'Multi-Currency Nomad Banking & FX',
    estimatedApprovalTime: '1 – 2 Business Days',
    typicalCommissionOrSavings: '$20 – $50 per active member account funded',
    portalUrl: 'https://wise.com/affiliates',
    requirements: [
      'FinTech or Travel Platform entity',
      'Affiliate network acceptance (Impact Radius / Partnerize)'
    ],
    stepByStepGuide: [
      '1. Register at wise.com/affiliates (via Impact.com).',
      '2. Obtain your Wise Partner Campaign Link ID.',
      '3. Paste into HotelsClub Admin > Digital Nomad & Visas under "FinTech Banking Partner".',
      '4. Members setting up multi-currency local accounts for their foreign visas generate automated affiliate commissions.'
    ]
  },
  {
    id: 'travel-vault-dividends',
    providerName: 'HotelsClub Vault & Profit Dividend Smart Engine',
    category: 'Closed-Loop Profit Sharing & Member Dividend Distribution',
    estimatedApprovalTime: 'Instant / Built-in Protocol',
    typicalCommissionOrSavings: 'Members receive annual cash dividend checks ($250 – $1,200) deposited directly onto their Visa Prepaid Card',
    portalUrl: 'https://hotelsclub.vip/vault',
    requirements: [
      'Active HotelsClub membership in good standing',
      'HotelsClub Reloadable Visa Card or PayPal account for deposit'
    ],
    stepByStepGuide: [
      '1. Every booking across hotels, private jets, yachts, and reloadable Visa card swipes generates Vault Equity Points.',
      '2. In Admin > Travel Vault, the platform operator views the total accumulated supplier profit pool.',
      '3. On December 31, click "Execute Annual Profit Dividend Payout".',
      '4. Cash is automatically credited onto each member\'s Visa Prepaid Card with instant email and SMS notifications.'
    ]
  },
  {
    id: 'le-collectionist-villas',
    providerName: 'Le Collectionist / Oliver’s Travels (Luxury Villas API)',
    category: 'Ultra-Luxury Villas & Private Chalets',
    estimatedApprovalTime: '1 – 2 Business Days',
    typicalCommissionOrSavings: '40% – 50% Member Wholesale Savings on Private Estates • 10% Platform Broker Fee',
    portalUrl: 'https://www.lecollectionist.com/en/travel-designers',
    requirements: [
      'B2B Travel Designer or VIP Club business registration',
      'Guest verification & concierge damage deposit protocol'
    ],
    stepByStepGuide: [
      '1. Register as a partner at lecollectionist.com/en/travel-designers or oliverstravels.com.',
      '2. In Developer Settings, copy your B2B Estate XML/REST API credentials.',
      '3. In HotelsClub Admin > Luxury Villas, paste your credentials and set your member discount pass-through.',
      '4. When a member books an estate, the on-site butler and private chef are notified to tailor arrival provisioning.'
    ]
  },
  {
    id: 'statusmatch-api',
    providerName: 'StatusMatch.com / Loylogic B2B API',
    category: 'Hotel & Airline Loyalty Elite Tier Matching',
    estimatedApprovalTime: '1 – 2 Business Days',
    typicalCommissionOrSavings: 'Instant Diamond/Platinum Status ($1,500+ in annual perks) • Platform keeps match fee split',
    portalUrl: 'https://www.statusmatch.com/business',
    requirements: [
      'Closed-Loop VIP Travel Club partnership',
      'Member tier verification bridge'
    ],
    stepByStepGuide: [
      '1. Apply for an enterprise partner account at statusmatch.com/business or loylogic.com.',
      '2. In Developer Settings, obtain your Status Bridge API Secret.',
      '3. In HotelsClub Admin > Status Match, paste your API token and define tier mappings (e.g. Gold ➔ Hilton Diamond).',
      '4. When a member requests a match, StatusMatch.com pushes instant tier upgrades directly to Hilton/Marriott/Star Alliance.'
    ]
  },
  {
    id: 'diamond-air-fasttrack',
    providerName: 'Diamond Air International / Marhaba (Fast-Track VIP)',
    category: 'Airport Fast-Track Immigration & Tarmac Meet-and-Greet',
    estimatedApprovalTime: '1 – 2 Business Days',
    typicalCommissionOrSavings: '50% Member Discount on VIP Jet Bridge Escorts • 15% Platform Commission',
    portalUrl: 'https://www.diamondair.co.uk/',
    requirements: [
      'Travel Agency or VIP Membership Club Partner registration',
      'Passenger flight manifest & arrival flight number forwarding'
    ],
    stepByStepGuide: [
      '1. Sign up at diamondair.co.uk or marhabaservices.com B2B partner portal.',
      '2. Copy your Agency Account ID and API Dispatch Token.',
      '3. In HotelsClub Admin > Fast-Track Immigration, paste your token and save.',
      '4. When a member books an arrival escort, the airport agent is dispatched to the jet bridge with a digital name board.'
    ]
  },
  {
    id: 'boatsetter-yachts',
    providerName: 'Boatsetter B2B API / Click&Boat (Yacht Charters)',
    category: 'Luxury Yacht & Catamaran Day Charters',
    estimatedApprovalTime: '1 – 2 Business Days',
    typicalCommissionOrSavings: '35% – 45% Member Savings on Captained Yacht Charters • 10% Platform Commission',
    portalUrl: 'https://www.boatsetter.com/affiliates',
    requirements: [
      'Travel Agency or VIP Concierge Partner Registration',
      'Passenger manifest & marine insurance waiver handling'
    ],
    stepByStepGuide: [
      '1. Sign up at boatsetter.com/affiliates or clickandboat.com partner portal.',
      '2. Copy your B2B Fleet Partner API Key and Webhook URL.',
      '3. In HotelsClub Admin > Yachts & Supercars, paste your key and adjust commission margins.',
      '4. When a member books a yacht, the licensed captain is dispatched and coordinates harbor boarding directly.'
    ]
  },
  {
    id: 'pruvo-autorebook',
    providerName: 'Pruvo For Business / Hotelmize (Auto-Rebook API)',
    category: 'Post-Booking Price Drop Tracking & Autonomous Re-Hedging',
    estimatedApprovalTime: '1 Business Day',
    typicalCommissionOrSavings: 'Members save an extra $70 – $240 per reservation after booking • Platform keeps split',
    portalUrl: 'https://www.pruvo.com/business',
    requirements: [
      'B2B Travel Platform or Agency entity',
      'Webhook endpoint to receive automated price-drop notifications'
    ],
    stepByStepGuide: [
      '1. Create an enterprise developer account at pruvo.com/business or hotelmize.com.',
      '2. In Developer Settings, copy your B2B API Token and configure your Webhook URL.',
      '3. In HotelsClub Admin > Auto-Rebooker, paste your Token and set your minimum rebook drop threshold ($25 min).',
      '4. When a member books a room, the engine monitors the rate 24/7. When the price drops, it automatically re-reserves at the lower rate and deposits the difference onto their Visa card.'
    ]
  },
  {
    id: 'lunajets-aviation',
    providerName: 'LunaJets / FlyXO API (Private Jet Empty Legs)',
    category: 'Private Aviation & Empty Leg Charter Brokerage',
    estimatedApprovalTime: '1 – 2 Business Days',
    typicalCommissionOrSavings: 'Up to 80% Off Whole Aircraft Charters • Platform earns $250 – $750 commission per flight',
    portalUrl: 'https://www.lunajets.com/en/b2b-partners',
    requirements: [
      'VIP Travel Club or Luxury Concierge Business Entity',
      'Passenger Passenger Manifest & Passport verification protocol'
    ],
    stepByStepGuide: [
      '1. Apply at lunajets.com/en/b2b-partners or flyxo.com/partners.',
      '2. Request B2B Empty Leg Feed API credentials (REST JSON Webhook).',
      '3. In HotelsClub Admin > Private Jets, paste your API Key and set your charter commission markups.',
      '4. When a member reserves a seat or whole jet, the FBO handling team coordinates executive tarmac access, catering, and pilot briefing.'
    ]
  },
  {
    id: 'airhelp-claims',
    providerName: 'AirHelp API (Flight Delay Legal Claims)',
    category: 'Flight Delay Legal Compensation (EU261 / US DOT)',
    estimatedApprovalTime: '1 Business Day',
    typicalCommissionOrSavings: 'Passengers win up to $650 cash • Platform earns $25–$45 affiliate bounty per claim',
    portalUrl: 'https://www.airhelp.com/en/affiliates/',
    requirements: [
      'Affiliate or B2B Partner registration',
      'Passenger Flight details (Flight #, Date, Delay length, Boarding pass)'
    ],
    stepByStepGuide: [
      '1. Register at airhelp.com/en/affiliates or apply for AirHelp Connect B2B API access.',
      '2. Copy your Affiliate Campaign ID or REST API Token.',
      '3. Paste it in Admin > Flight Delay Claims and click Save.',
      '4. When a member experiences a flight delay of 3+ hours, they enter their flight number in your Member Claim Center.',
      '5. AirHelp legal attorneys automatically sue or negotiate with the airline on a no-win no-fee basis.',
      '6. When the airline pays out, cash is deposited into the member\'s Visa card or PayPal, and your platform receives the referral commission.'
    ]
  },
  {
    id: 'safetywing-insurance',
    providerName: 'SafetyWing / Allianz Partner (Global Travel Insurance)',
    category: 'Travel Medical & Trip Cancellation Insurance',
    estimatedApprovalTime: 'Instant Partner Sandbox / 24h Live',
    typicalCommissionOrSavings: '15% – 20% recurring commission on policy sales or 100% pass-through discount',
    portalUrl: 'https://safetywing.com/partners',
    requirements: [
      'Partner registration',
      'Payout account (PayPal / Bank Transfer)'
    ],
    stepByStepGuide: [
      '1. Sign up at safetywing.com/partners or allianz-partners.com.',
      '2. Obtain your Partner Tracking Token or Embed API Secret.',
      '3. Configure your member discount pass-through in Admin > Travel Insurance.',
      '4. Members receive instant policy PDFs with border control QR verification for international visa entry.'
    ]
  },
  {
    id: 'stripe-issuing',
    providerName: 'Stripe Issuing (Co-Branded Reloadable Visa Cards)',
    category: 'Banking-as-a-Service & Card Issuing',
    estimatedApprovalTime: '1 – 2 Business Days',
    typicalCommissionOrSavings: 'Earn 1.2% – 1.6% Interchange Revenue on every member card swipe',
    portalUrl: 'https://dashboard.stripe.com/issuing',
    requirements: [
      'Active Stripe account in good standing',
      'Business Registration Number / Tax ID (EIN / VAT)',
      'Custom Card Artwork (PDF or PNG 1013x638px at 300 DPI)',
      'Cardholder Terms of Service & Privacy Policy'
    ],
    stepByStepGuide: [
      '1. Log into your Stripe Dashboard and navigate to the "Issuing" tab.',
      '2. Click "Request Access" for Physical Card Issuing and submit your business entity details.',
      '3. In "Card Designs", upload your HotelsClub metallic Gold/Platinum card art with your logo.',
      '4. Copy your Secret Key (sk_live_...) and Webhook Secret from Developer Settings.',
      '5. Paste the keys in your HotelsClub Admin Console under "Prepaid Visa Manager" and click Publish.',
      '6. When members order a Visa card, Stripe automatically prints and ships it via USPS with real-time tracking.'
    ]
  }
];

export const MOCK_ESIM_PACKAGES: EsimPackage[] = [
  {
    id: 'esim-usa-5gb',
    countryCode: 'US',
    countryName: 'United States',
    flagEmoji: '🇺🇸',
    region: 'Americas',
    dataAmount: '5 GB High-Speed',
    validityDays: 30,
    publicRetailPrice: 16.00,
    memberWholesalePrice: 8.50,
    networkSpeed: '5G / 4G LTE',
    carrierPartners: 'AT&T / T-Mobile 5G',
    instantQrDelivery: true,
  }
];

export const MOCK_VISA_ACCOUNT: VisaCardAccount = {
  id: 'visa-acc-9824',
  userId: 'demo-vip-member-777',
  cardNumberMasked: '•••• •••• •••• 8842',
  cardholderName: 'ALEX HARRISON',
  expiry: '09/29',
  cvvMasked: '•••',
  balance: 450.00,
  currency: 'USD',
  status: 'active',
  tier: 'gold',
  cardType: 'Physical Plastic Chip & PIN',
  cardDesign: 'Gold VIP Metallic',
  autoReloadEnabled: true,
  autoReloadAmount: 100.00,
};

export const MEMBERSHIP_TIERS: TierPlan[] = [
  {
    id: 'free',
    name: 'Explorer (Free)',
    badgeColor: 'bg-slate-500',
    priceMonthly: 0,
    priceAnnual: 0,
    wholesaleHotelDiscount: 'Up to 15% Off',
    perksIncluded: [
      'Search live hotel rates',
      'Preview wholesale pricing',
      'Flight delay compensation scanner',
      'Standard customer support'
    ]
  },
  {
    id: 'nomad',
    name: 'Global Nomad Passport',
    badgeColor: 'bg-teal-600',
    priceMonthly: 29.99,
    priceAnnual: 279,
    wholesaleHotelDiscount: 'Up to 50% Off (Monthly Coliving & Long-Stays)',
    isPopular: true,
    perksIncluded: [
      'Free 10GB Global 5G Travel eSIM auto-renewed monthly',
      'SafetyWing Travel Medical Insurance included',
      'Digital Nomad Visa Application Concierge (Spain, Portugal, Dubai, Thailand)',
      'Schengen 90/180-Day Automated Compliance Sentinel',
      'Curated monthly coliving spaces with verified 300+ Mbps Fiber Wi-Fi',
      'HotelsClub Reloadable Visa Card with 0% Foreign Transaction Fees',
      '3x Travel Vault Dividend Multiplier'
    ]
  },
  {
    id: 'silver',
    name: 'Silver Club',
    badgeColor: 'bg-slate-400',
    priceMonthly: 9.99,
    priceAnnual: 89,
    wholesaleHotelDiscount: 'Up to 35% Off',
    perksIncluded: [
      'Access to 400,000+ wholesale hotels',
      '2x Travel Vault Dividend Multiplier',
      'Car rental discounts up to 25%',
      'Global eSIM travel data discounts',
      'Flight delay legal claim assistance ($650 compensation)',
      'Digital member card & app pass'
    ]
  },
  {
    id: 'gold',
    name: 'Gold VIP',
    badgeColor: 'bg-amber-500',
    priceMonthly: 19.99,
    priceAnnual: 179,
    wholesaleHotelDiscount: 'Up to 55% Off',
    perksIncluded: [
      'Maximum wholesale rates (1M+ properties)',
      '4x Travel Vault Dividend Multiplier (Annual Cash Payout to Visa)',
      'Curated Ultra-Luxury Villas & Private Chalets (45% Off)',
      'Wholesale cruise closed-loop pricing + $150 Onboard Credit',
      'Hilton Honors Diamond & Marriott Platinum Status Matches',
      'VIP Airport Fast-Track Immigration Escort Discounts ($85 flat rate)',
      'Autonomous Post-Booking Price Drop Re-Booker (Cashback to Visa)',
      'Supercar & Luxury Yacht Day Charters (Up to 45% Off)',
      'Private Jet Empty Leg Member Access (Up to 80% Off)',
      'Co-Branded Rechargeable Visa Prepaid Card included',
      'Proactive AI Concierge Itinerary Gap Alerts',
      'Physical holographic Photo ID card shipped free',
      'Family pass (Up to 4 sub-members)'
    ]
  },
  {
    id: 'platinum',
    name: 'Platinum Elite',
    badgeColor: 'bg-purple-600',
    priceMonthly: 39.99,
    priceAnnual: 349,
    wholesaleHotelDiscount: 'Up to 70% Off',
    perksIncluded: [
      'Guaranteed lowest rate price match + 10%',
      '8x Travel Vault Dividend Multiplier (Maximum Club Profit Share)',
      'Complimentary Private Villa Butler & Chef on all estate bookings',
      'Complimentary Star Alliance Gold Airline Status Match included',
      'Complimentary VIP Airport Fast-Track Pass annually',
      'VIP Airport Lounge access discounts ($32 flat pass)',
      'Complimentary Essential Travel Medical Insurance included',
      'Wholesale cruises + $300 Free Onboard Credit bonus',
      'Complimentary Supercar Track Day or Yacht Sunset Cruise',
      'Private Jet Empty Leg Whole Aircraft Charter Discounts',
      'Free 5GB Global Travel eSIM Data Pass every year',
      'Heavy Titanium Physical Visa Prepaid Card included',
      'Dedicated Proactive AI Concierge + personal travel agent'
    ]
  }
];

export const MOCK_CRUISES: CruiseItinerary[] = [
  {
    id: 'icon-caribbean',
    shipName: 'Icon of the Seas',
    cruiseLine: 'Royal Caribbean',
    title: '7-Night Eastern Caribbean & Perfect Day at CocoCay',
    destination: 'Eastern Caribbean',
    departurePort: 'Miami, Florida',
    durationNights: 7,
    portsOfCall: ['Miami, FL', 'Philipsburg, St. Maarten', 'Charlotte Amalie, St. Thomas', 'Perfect Day at CocoCay, Bahamas'],
    departureDates: ['2026-10-18', '2026-11-08', '2026-12-06'],
    thumbnail: 'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 1890,
    memberPriceStarting: 1140,
    savingsPercentage: 40,
    onboardCredit: 250,
    cabins: [
      {
        id: 'balcony-ocean',
        name: 'Spacious Ocean View Balcony Stateroom',
        category: 'Balcony',
        description: 'Private glass balcony with unobstructed Caribbean ocean views, sitting area with sofa bed, and luxury bedding.',
        publicBrochurePrice: 2240,
        wholesaleMemberPrice: 1390,
        onboardCreditBonus: 250,
        freePerks: ['$250 Free Onboard Spending Credit', 'Free Premium Wi-Fi Package', 'Complimentary Specialty Dining for 2'],
        availableCount: 5,
      }
    ]
  }
];

export const MOCK_LOUNGES: AirportLounge[] = [
  {
    id: 'jfk-clubhouse',
    airportCode: 'JFK',
    airportName: 'New York John F. Kennedy International',
    terminal: 'Terminal 4, Concourse A',
    loungeName: 'The Skyview Club & Oasis Lounge',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
    amenities: ['Buffet Dining by Master Chefs', 'Craft Beer & Premium Spirits Bar', 'Private Shower Suites', 'High-Speed Wi-Fi', 'Quiet Nap Pods'],
    walkInPrice: 65,
    memberPassPrice: 32,
    operatingHours: '05:00 - 23:30 Daily',
    locationDetails: 'Airside - Post-security, adjacent to Gate A5.',
  }
];

export const MOCK_CARD_ORDERS: PhysicalCardOrder[] = [
  {
    id: 'CARD-ORD-901',
    userId: 'demo-vip-member-777',
    memberName: 'Alex Harrison',
    memberId: 'HC-9824-VIP',
    tier: 'gold',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    foilStyle: 'metallic_gold',
    cardType: 'Co-Branded Visa Prepaid',
    shippingAddress: {
      street: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'OR',
      zip: '97477',
      country: 'United States',
    },
    status: 'printing',
    trackingNumber: 'USPS-9400111899562534882190',
    carrier: 'USPS First Class Priority',
    orderedAt: '2026-08-25',
  }
];

export const MOCK_HOTELS: Hotel[] = [
  {
    id: 'bellagio-vegas',
    name: 'The Grand Bellagio & Casino Resort',
    tagline: 'Iconic luxury fountains, five-star dining & prime Strip location',
    description: 'Experience unparalleled world-class hospitality on the Las Vegas Strip. Featuring lavish fountains, botanical gardens, upscale spa, fine dining by Michelin-starred chefs, and opulent suites.',
    city: 'Las Vegas',
    stateCountry: 'Nevada, USA',
    address: '3600 S Las Vegas Blvd, Las Vegas, NV 89109',
    stars: 5,
    rating: 4.8,
    reviewCount: 3420,
    thumbnail: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPricePerNight: 389,
    memberPricePerNight: 198,
    savingsPercentage: 49,
    category: 'Luxury Resort',
    featured: true,
    amenities: ['Casino', 'Full Spa', '5 Outdoor Pools', 'Free High-Speed WiFi', 'Valet Parking', 'Fine Dining'],
    rooms: [
      {
        id: 'deluxe-king',
        name: 'Deluxe Fountain View King Suite',
        description: 'Spectacular views of the world-famous fountains with plush king pillow-top bed and Italian marble bathroom.',
        bedType: '1 King Bed',
        maxGuests: 2,
        publicRetailPrice: 389,
        wholesaleMemberPrice: 198,
        availableCount: 4,
        amenities: ['Fountain View', 'Marble Bath', 'Espresso Machine', 'Smart TV'],
        refundable: true
      }
    ]
  }
];

export const MOCK_PERKS: PerkDeal[] = [
  {
    id: 'hertz-car-rental',
    title: 'Up to 30% Off Premium Car Rentals + Free Upgrade',
    partnerName: 'Hertz Gold Plus Rewards',
    category: 'Car Rental',
    discountText: '30% OFF',
    description: 'Save big on SUV, luxury sedan, and minivan rentals worldwide with waived additional driver fees and instant skip-the-counter access.',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    terms: 'Valid at participating airport and neighborhood locations. Must present digital member ID card.',
    code: 'HOTELCLUB30',
    location: 'Nationwide & Global Locations',
    rating: 4.8,
    redemptionType: 'online_code'
  }
];
