const fs = require('fs');
const path = require('path');

const mockDataPath = path.join(__dirname, '..', 'src', 'lib', 'mockData.ts');
let content = fs.readFileSync(mockDataPath, 'utf8');

// 1. Expanded MOCK_VILLAS
const expandedVillasCode = `export const MOCK_VILLAS: LuxuryVillaEstate[] = [
  {
    id: 'villa-stbarts-etoile',
    name: 'Villa L’Étoile & Private Beach Estate',
    destination: 'St. Barts',
    region: 'Flamands Beach',
    country: 'Caribbean',
    bedrooms: 6,
    bathrooms: 7,
    maxGuests: 12,
    propertyType: 'Beachfront Villa',
    publicPricePerNight: 5800,
    memberPricePerNight: 3200,
    savingsPercentage: 45,
    amenities: ['Heated Infinity Pool overlooking Flamands Bay', 'Direct Private Beach Boardwalk', 'Outdoor Cinema & Teppanyaki Grill', 'State-of-the-art Gym & Spa', 'Air Conditioned Master Suites with Terrace'],
    staffIncluded: ['Private French Gourmet Chef', 'Full-Time Butler & Bartender', 'Daily Housekeeping & Turndown', 'Dedicated Airport Chauffeur'],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-lake-como-balbianello',
    name: 'Villa del Lago & Private Riva Pier',
    destination: 'Lake Como',
    region: 'Tremezzina & Bellagio',
    country: 'Italy',
    bedrooms: 7,
    bathrooms: 8,
    maxGuests: 14,
    propertyType: 'Cliffside Retreat',
    publicPricePerNight: 6500,
    memberPricePerNight: 3800,
    savingsPercentage: 42,
    amenities: ['Private Pier with Classic Riva Aquarama Boat', 'Heated Infinity Pool overlooking Bellagio', 'Century-Old Botanical Gardens', 'Wine Cellar with Vintage Barolo & Chianti', 'Alfresco Dining Loggia with Panoramic Lake Views'],
    staffIncluded: ['Italian Executive Chef & Pastry Cook', 'Private Riva Yacht Captain', 'Head Butler & Concierge Host', 'Daily Housekeeping & Laundry'],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-amalfi-positano-terrazza',
    name: 'Villa Positano Belvedere & Clifftop Spa',
    destination: 'Amalfi Coast',
    region: 'Positano Clifftops',
    country: 'Italy',
    bedrooms: 5,
    bathrooms: 6,
    maxGuests: 10,
    propertyType: 'Cliffside Retreat',
    publicPricePerNight: 4900,
    memberPricePerNight: 2850,
    savingsPercentage: 42,
    amenities: ['Clifftop Hydrotherapy Pool with Mediterranean Views', 'Funicular Lift to Private Sea Platform', 'Wood-Burning Pizza Oven & Sunset Pergola', 'Panoramic Lemon Grove Terrace', 'Technogym Fitness Suite with Sea View'],
    staffIncluded: ['Local Campanian Private Chef', 'Villa Host & Sommelier', 'Daily Maid Service & Turndown', 'Private Speedboat Captain for Capri Daytrips'],
    images: [
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-santorini-oia-celestia',
    name: 'Villa Oia Celestia Caldera Sanctuary',
    destination: 'Santorini',
    region: 'Oia Clifftops',
    country: 'Greece',
    bedrooms: 4,
    bathrooms: 5,
    maxGuests: 8,
    propertyType: 'Cliffside Retreat',
    publicPricePerNight: 3800,
    memberPricePerNight: 2100,
    savingsPercentage: 45,
    amenities: ['Heated Cave Pool & Infinity Caldera Jacuzzi', 'Sunset Viewing Pavilion over the Aegean', 'Wine Tasting Room with Assyrtiko Vintages', 'Luxury Cycladic Cave Suites', 'Private Helipad Access'],
    staffIncluded: ['Cycladic Private Chef (Greek Gourmet)', 'VIP Villa Host & Sommelier', 'Daily Housekeeping & Fresh Linen Service', 'Airport & Port Luxury Chauffeur'],
    images: [
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-ibiza-can-skye',
    name: 'Can Skye Ultra-Modernist Sunset Estate',
    destination: 'Ibiza',
    region: 'Cala d’Hort & Es Vedrà',
    country: 'Spain',
    bedrooms: 6,
    bathrooms: 7,
    maxGuests: 12,
    propertyType: 'Beachfront Villa',
    publicPricePerNight: 5200,
    memberPricePerNight: 2950,
    savingsPercentage: 43,
    amenities: ['25m Olympic Infinity Pool facing Es Vedrà', 'Pioneer DJ Booth & Void Acoustics Pro Sound System', 'Outdoor Daybed Lounge & Fire Pit', 'Yoga Pavilion & Cold Plunge Wellness Suite', 'Biometric Secure Gated Perimeter'],
    staffIncluded: ['Private Chef (Organic Mediterranean & Asian Fusion)', 'Resident Butler & Mixologist', 'Night Security Guard', 'VIP Island Concierge (Club & Beach Club Tables)'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-tuscany-val-dorcia',
    name: 'Tenuta San Giorgio & Historic Vineyards',
    destination: 'Tuscany',
    region: 'Val d’Orcia / Montalcino',
    country: 'Italy',
    bedrooms: 8,
    bathrooms: 9,
    maxGuests: 16,
    propertyType: 'Vineyard Estate',
    publicPricePerNight: 4600,
    memberPricePerNight: 2500,
    savingsPercentage: 46,
    amenities: ['Private Olive Groves & Brunello Vineyards', 'Heated Cypress-Lined Swimming Pool', 'Professional Molteni Culinary Kitchen', 'Clay Tennis Court & Bocce Pitch', 'Ancient Stone Wine Tasting Cellar'],
    staffIncluded: ['Master Tuscan Nonna & Sous Chef', 'Certified In-House Sommelier', 'Daily Housekeeper & Breakfast Cook', 'Grounds & Pool Caretaker'],
    images: [
      'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-turks-grace-bay',
    name: 'Villa La Palmeraie Oceanfront Compound',
    destination: 'Turks & Caicos',
    region: 'Grace Bay Beach',
    country: 'Caribbean',
    bedrooms: 7,
    bathrooms: 8,
    maxGuests: 14,
    propertyType: 'Beachfront Villa',
    publicPricePerNight: 6200,
    memberPricePerNight: 3600,
    savingsPercentage: 42,
    amenities: ['120ft Private White Sand Beachfront', 'Twin Oceanfront Infinity Pools & Sun Loungers', 'Private Boat Dock & 2x Sea-Doo Jet Skis', 'Outdoor Beachfront Cinema Screen', 'Pickleball Court & Beach Volleyball'],
    staffIncluded: ['Gourmet Island Chef & Grillmaster', 'Dedicated Butler Team (2 Staff)', 'Certified Watersports Instructor', 'Daily Housekeeping & Turndown'],
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-courchevel-chalet-blanc',
    name: 'Chalet Blanc Belvédère Ski-In / Ski-Out',
    destination: 'Courchevel 1850',
    region: 'Bellecôte Piste',
    country: 'France',
    bedrooms: 6,
    bathrooms: 7,
    maxGuests: 12,
    propertyType: 'Alpine Ski Chalet',
    publicPricePerNight: 7500,
    memberPricePerNight: 4200,
    savingsPercentage: 44,
    amenities: ['Direct Bellecôte Piste Ski-In / Ski-Out Access', 'Indoor Heated Swimming Pool & Jacuzzi', 'Finnish Sauna, Hammam & Massage Treatment Room', 'Private 12-Seat Cinema Room', 'Heated Ski Boot Room with Direct Slopes Access'],
    staffIncluded: ['Michelin-Trained French Alpine Chef', 'Chalet Manager & Formal Butler', 'Dedicated Ski Butler & Equipment Technician', 'Chauffeur with 4x4 Luxury V-Class Mercedes'],
    images: [
      'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-aspen-red-mountain',
    name: 'Red Mountain Monarch Ski Lodge',
    destination: 'Aspen, CO',
    region: 'Red Mountain',
    country: 'USA',
    bedrooms: 6,
    bathrooms: 8,
    maxGuests: 12,
    propertyType: 'Alpine Ski Chalet',
    publicPricePerNight: 6800,
    memberPricePerNight: 3900,
    savingsPercentage: 43,
    amenities: ['Panoramic Views of Ajax Mountain & Downtown Aspen', '12-Person Outdoor Cedar Hot Tub', 'Custom Wine Room & Wet Bar Lounge', 'Ski Locker Room with Boot Warmers', 'Radiant-Heated Stone Terraces & Fire Pit'],
    staffIncluded: ['Private Executive Chef', 'Full-Time Butler & Beverage Specialist', 'Daily Housekeeper', 'Dedicated Chauffeur with Cadillac Escalade ESV'],
    images: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-bali-uluwatu-sanctuary',
    name: 'The Ungasan Clifftop Sanctuary & Ocean Pavilion',
    destination: 'Bali',
    region: 'Uluwatu Clifftops',
    country: 'Indonesia',
    bedrooms: 5,
    bathrooms: 6,
    maxGuests: 10,
    propertyType: 'Cliffside Retreat',
    publicPricePerNight: 3200,
    memberPricePerNight: 1750,
    savingsPercentage: 45,
    amenities: ['30-Meter Clifftop Infinity Pool overlooking the Indian Ocean', 'Direct Inclinator Access to Private Beach Club', 'Open-Air Living Teak Sala & Dining Pavilion', 'Ocean-Facing Master Suites with Outdoor Stone Baths', 'Private Grass Tennis Court'],
    staffIncluded: ['Private Balinese Gourmet Chef', 'Dedicated 24/7 Personal Butler', 'On-Site Spa Therapists', 'Private Chauffeur with Luxury Alphard Van'],
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-phuket-aman-pavilion',
    name: 'Villa Amanpuri Royal Beachfront Compound',
    destination: 'Phuket',
    region: 'Pansea Beach',
    country: 'Thailand',
    bedrooms: 6,
    bathrooms: 7,
    maxGuests: 12,
    propertyType: 'Beachfront Villa',
    publicPricePerNight: 4500,
    memberPricePerNight: 2400,
    savingsPercentage: 47,
    amenities: ['Direct Access to Private Golden Sand Cove', 'Midnight-Blue Tiled Infinity Pool', 'Authentic Ayutthaya Teak Architectural Pavilions', 'Steam Room & Open-Air Massage Pavilions', 'Private Speedboat Charter for Phi Phi & Phang Nga'],
    staffIncluded: ['Executive Thai & International Master Chef', 'Head Butler & Concierge Host', 'Villa Host & Housekeeping Staff', 'Night Security & Beach Attendants'],
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  },
  {
    id: 'villa-mallorca-tramuntana',
    name: 'Son Mir Clifftop Finca & Sea Estate',
    destination: 'Mallorca',
    region: 'Serra de Tramuntana / Deià',
    country: 'Spain',
    bedrooms: 5,
    bathrooms: 6,
    maxGuests: 10,
    propertyType: 'Vineyard Estate',
    publicPricePerNight: 3900,
    memberPricePerNight: 2150,
    savingsPercentage: 45,
    amenities: ['UNESCO Heritage Tramuntana Mountain & Sea Views', 'Infinity Edge Swimming Pool with Sun Decks', 'Century-Old Olive Oil Mill & Bodega Cellar', 'Outdoor Summer Kitchen with Wood Oven', 'Helicopter Landing Pad on Estate Grounds'],
    staffIncluded: ['Private Spanish Chef (Tapas & Paella Specialist)', 'Butler & Bartender', 'Daily Maid Service & Turndown', 'Airport & Palma Chauffeur'],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'
    ],
    featured: true,
  }
];`;

// 2. Expanded MOCK_YACHTS
const expandedYachtsCode = `export const MOCK_YACHTS: LuxuryYachtCharter[] = [
  {
    id: 'yacht-miami-sunseeker',
    name: '75ft Sunseeker Predator "Aura VIP"',
    lengthFeet: 75,
    builder: 'Sunseeker International',
    location: 'Miami Beach Marina, South Beach',
    city: 'Miami, FL',
    maxGuests: 12,
    staterooms: 3,
    crewCount: 2,
    includesCaptain: true,
    halfDayRetailPrice: 3800,
    halfDayMemberPrice: 2200,
    fullDayRetailPrice: 6500,
    fullDayMemberPrice: 3900,
    amenities: ['Licensed USCG Captain & First Mate', 'Open Bar with Top-Shelf Spirits', 'Full Sound System with Bluetooth', 'Air Conditioned Salon & Master Suite', 'Towel & Ice Service Included'],
    waterToys: ['2x Seabob Underwater Scooters', 'Inflatable Floating Island', 'Paddleboards & Snorkel Gear'],
    image: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d17?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    id: 'yacht-monaco-azimut',
    name: '105ft Azimut Grande "Sovereign Blue"',
    lengthFeet: 105,
    builder: 'Azimut Yachts',
    location: 'Port Hercule, Monaco',
    city: 'Monaco / Côte d’Azur',
    maxGuests: 12,
    staterooms: 5,
    crewCount: 5,
    includesCaptain: true,
    halfDayRetailPrice: 8500,
    halfDayMemberPrice: 5100,
    fullDayRetailPrice: 14500,
    fullDayMemberPrice: 8800,
    amenities: ['Flybridge Jacuzzi with Champagne Bar', 'Dedicated Michelin-Trained Yacht Chef', 'Master Stateroom with Private Balcony', 'Stabilizers at Anchor & Underway', 'High-Speed Starlink Maritime Wi-Fi'],
    waterToys: ['Williams 445 Jet Tender', '2x Yamaha WaveRunners', 'Fliteboard eFoil', 'Seabobs & Inflatable Sea Pool'],
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    id: 'yacht-amalfi-riva',
    name: '88ft Riva Folgore "Dolce Vita"',
    lengthFeet: 88,
    builder: 'Riva Yacht / Ferretti Group',
    location: 'Marina Grande, Capri & Positano',
    city: 'Amalfi Coast, Italy',
    maxGuests: 10,
    staterooms: 4,
    crewCount: 3,
    includesCaptain: true,
    halfDayRetailPrice: 6200,
    halfDayMemberPrice: 3800,
    fullDayRetailPrice: 10500,
    fullDayMemberPrice: 6400,
    amenities: ['Polished Mahogany & Carbon Fiber Interior', 'Private Sommelier & Campanian Lunch Host', 'Full Bimini Sunshade on Bow & Stern', 'Dolce & Gabbana Casa Linen Sets', 'Submersible Swim Platform'],
    waterToys: ['Williams SportJet 395', '2x Seabob F5S', 'Snorkel Gear for Blue Grotto', 'Paddleboards'],
    image: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    id: 'yacht-ibiza-princess',
    name: '95ft Princess Y95 "Nomad Sky"',
    lengthFeet: 95,
    builder: 'Princess Yachts',
    location: 'Marina Botafoch, Ibiza',
    city: 'Ibiza & Formentera',
    maxGuests: 12,
    staterooms: 4,
    crewCount: 4,
    includesCaptain: true,
    halfDayRetailPrice: 7200,
    halfDayMemberPrice: 4400,
    fullDayRetailPrice: 12000,
    fullDayMemberPrice: 7200,
    amenities: ['Pioneer DJ Deck on Flybridge', 'Full Cocktail Bar with Resident Mixologist', 'Bespoke Tapas & Seafood Catering', 'Panoramic Floor-to-Ceiling Windows', 'Daybeds with Misting Fans'],
    waterToys: ['Castoldi Jet Tender', '2x Sea-Doo Spark Trixx', 'Awake Ravik Electric Surfboard', 'Seabobs'],
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    id: 'yacht-dubai-benetti',
    name: '120ft Benetti Oasis "Desert Pearl"',
    lengthFeet: 120,
    builder: 'Benetti Yachts',
    location: 'Dubai Harbour Marina',
    city: 'Dubai, UAE',
    maxGuests: 14,
    staterooms: 5,
    crewCount: 6,
    includesCaptain: true,
    halfDayRetailPrice: 9800,
    halfDayMemberPrice: 5900,
    fullDayRetailPrice: 16800,
    fullDayMemberPrice: 10200,
    amenities: ['Flush Deck Infinity Pool with Glass Bottom', 'Main Deck Beach Club with Fold-Out Wings', 'Full Teppanyaki Bar & VIP Dining Salon', 'Private Gym & Turkish Steam Room', 'Starlink Maritime Ultra Connectivity'],
    waterToys: ['Novurania 24ft Chase Boat', '3x Yamaha FX SVHO Jet Skis', '2x Fliteboards', 'Full Deep-Sea Fishing Gear'],
    image: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d17?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  }
];`;

// 3. Expanded MOCK_SUPERCARS
const expandedSupercarsCode = `export const MOCK_SUPERCARS: SupercarRental[] = [
  {
    id: 'car-ferrari-f8',
    makeModel: 'Ferrari F8 Tributo (710 HP)',
    category: 'Supercar',
    city: 'Las Vegas, NV & Miami, FL',
    location: 'Hotel Doorstep VIP Delivery',
    horsepower: 710,
    zeroToSixtyMph: '2.9s',
    dailyRetailPrice: 1690,
    dailyMemberPrice: 950,
    includedMilesPerDay: 100,
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80',
    deliveryAvailable: true,
    features: ['Twin-Turbo 3.9L V8', 'Full Carbon Fiber Package', 'Exhaust Valve Switch', 'Free Concierge Hotel Delivery'],
  },
  {
    id: 'car-lambo-huracan-spyder',
    makeModel: 'Lamborghini Huracán EVO Spyder (640 HP)',
    category: 'Supercar',
    city: 'Miami, FL & Los Angeles, CA',
    location: 'VIP Airport FBO or Hotel Delivery',
    horsepower: 640,
    zeroToSixtyMph: '3.1s',
    dailyRetailPrice: 1750,
    dailyMemberPrice: 990,
    includedMilesPerDay: 100,
    image: 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80',
    deliveryAvailable: true,
    features: ['Naturally Aspirated 5.2L V10', 'Electrically Operated Soft Top', 'Sport Exhaust with Corsa Mode', 'Apple CarPlay & Carbon Ceramics'],
  },
  {
    id: 'car-mclaren-720s',
    makeModel: 'McLaren 720S Performance (710 HP)',
    category: 'Supercar',
    city: 'Las Vegas, NV & Scottsdale, AZ',
    location: 'Strip Hotel Doorstep Delivery',
    horsepower: 710,
    zeroToSixtyMph: '2.8s',
    dailyRetailPrice: 1850,
    dailyMemberPrice: 1050,
    includedMilesPerDay: 100,
    image: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&w=1200&q=80',
    deliveryAvailable: true,
    features: ['Dihedral Butterfly Doors', '4.0L Twin-Turbo V8', 'Variable Drift Control', 'Bowers & Wilkins Audio'],
  },
  {
    id: 'car-porsche-gt3rs',
    makeModel: 'Porsche 911 GT3 RS (Weissach Package)',
    category: 'Supercar',
    city: 'Dubai, UAE & Zurich, Switzerland',
    location: 'Airport VIP Terminal Delivery',
    horsepower: 518,
    zeroToSixtyMph: '3.0s',
    dailyRetailPrice: 1950,
    dailyMemberPrice: 1100,
    includedMilesPerDay: 120,
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80',
    deliveryAvailable: true,
    features: ['Naturally Aspirated 4.0L Flat-6', 'Active Aerodynamic DRS Rear Wing', 'Carbon Roll Cage & Bucket Seats', 'PDK 7-Speed Dual-Clutch'],
  },
  {
    id: 'car-rolls-cullinan',
    makeModel: 'Rolls-Royce Cullinan Black Badge (591 HP)',
    category: 'Luxury SUV',
    city: 'New York, NY & London, UK',
    location: 'Teterboro FBO or Hotel Delivery',
    horsepower: 591,
    zeroToSixtyMph: '4.5s',
    dailyRetailPrice: 2200,
    dailyMemberPrice: 1250,
    includedMilesPerDay: 100,
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80',
    deliveryAvailable: true,
    features: ['Twin-Turbo 6.75L V12', 'Shooting Star Starlight Headliner', 'Viewing Suite Tailgate Leather Seats', 'Whisper-Quiet Magic Carpet Ride'],
  }
];`;

// 4. Expanded MOCK_PRIVATE_JETS
const expandedJetsCode = `export const MOCK_PRIVATE_JETS: PrivateJetEmptyLeg[] = [
  {
    id: 'jet-opf-teb-300',
    aircraftType: 'Bombardier Challenger 300',
    category: 'Super Midsize',
    operator: 'VistaJet / XO Private Fleet',
    tailNumber: 'N882VJ',
    departureAirportCode: 'OPF',
    departureAirportName: 'Miami Opa-Locka Executive Airport',
    departureCity: 'Miami, FL',
    arrivalAirportCode: 'TEB',
    arrivalAirportName: 'Teterboro Executive Airport',
    arrivalCity: 'New York, NY',
    departureDate: '2026-10-12',
    departureTime: '14:30 EST',
    flightDuration: '2h 45m',
    maxPassengers: 8,
    wholeJetRetailPrice: 28500,
    wholeJetMemberPrice: 8900,
    perSeatMemberPrice: 1250,
    savingsPercentage: 69,
    amenities: ['Dom Pérignon Champagne & Full Bar', 'High-Speed Ka-Band Wi-Fi', 'Private Enclosed Lavatory', 'Pet Friendly In-Cabin', 'Direct Tarmac VIP Boarding'],
    image: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'Atlantic Aviation FBO (No TSA Lines)',
    status: 'available'
  },
  {
    id: 'jet-fab-nce-8x',
    aircraftType: 'Dassault Falcon 8X',
    category: 'Heavy Long-Range',
    operator: 'NetJets Europe',
    tailNumber: 'G-FLCN',
    departureAirportCode: 'FAB',
    departureAirportName: 'London Farnborough Airport',
    departureCity: 'London, UK',
    arrivalAirportCode: 'NCE',
    arrivalAirportName: 'Nice Côte d’Azur International',
    arrivalCity: 'Nice / Monaco',
    departureDate: '2026-10-14',
    departureTime: '11:15 BST',
    flightDuration: '1h 55m',
    maxPassengers: 14,
    wholeJetRetailPrice: 34000,
    wholeJetMemberPrice: 11200,
    perSeatMemberPrice: 1480,
    savingsPercentage: 67,
    amenities: ['Three-Zone Executive Cabin', 'Lie-Flat Berthable Beds', 'Full Galley with Caviar Service', 'Starlink Aviation Ultra Wi-Fi', 'VIP Customs Clearance at Aircraft'],
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'TAG Farnborough Executive Terminal',
    status: 'available'
  },
  {
    id: 'jet-vny-las-cit',
    aircraftType: 'Cessna Citation Longitude',
    category: 'Super Midsize',
    operator: 'Flexjet Private Fleet',
    tailNumber: 'N440FX',
    departureAirportCode: 'VNY',
    departureAirportName: 'Van Nuys Airport',
    departureCity: 'Los Angeles, CA',
    arrivalAirportCode: 'LAS',
    arrivalAirportName: 'Harry Reid International Airport',
    arrivalCity: 'Las Vegas, NV',
    departureDate: '2026-10-16',
    departureTime: '16:00 PST',
    flightDuration: '0h 50m',
    maxPassengers: 8,
    wholeJetRetailPrice: 16800,
    wholeJetMemberPrice: 4900,
    perSeatMemberPrice: 680,
    savingsPercentage: 71,
    amenities: ['Soundproofing Whisper Cabin', 'Artisan Leather Club Recliners', 'Complimentary Vintage Spirits Bar', 'Fast Tarmac Valet Parking', 'Zero Luggage Weight Restrictions'],
    image: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e873?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'Signature Flight Support VNY West',
    status: 'available'
  },
  {
    id: 'jet-gva-lbg-300e',
    aircraftType: 'Embraer Phenom 300E',
    category: 'Light Jet',
    operator: 'Luxaviation Group',
    tailNumber: 'F-GPHN',
    departureAirportCode: 'GVA',
    departureAirportName: 'Geneva Cointrin Airport',
    departureCity: 'Geneva, Switzerland',
    arrivalAirportCode: 'LBG',
    arrivalAirportName: 'Paris Le Bourget Airport',
    arrivalCity: 'Paris, France',
    departureDate: '2026-10-18',
    departureTime: '09:30 CET',
    flightDuration: '1h 05m',
    maxPassengers: 7,
    wholeJetRetailPrice: 18200,
    wholeJetMemberPrice: 5400,
    perSeatMemberPrice: 790,
    savingsPercentage: 70,
    amenities: ['Best-in-Class Cabin Altitude', 'Swiss Chocolate & Champagne Basket', 'High-Speed Bongiovi Sound System', 'Private Enclosed Aft Toilet', '5-Minute Boarding from Lounge'],
    image: 'https://images.unsplash.com/photo-1583416750470-965b2707b355?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'Jet Aviation Geneva VIP Salon',
    status: 'available'
  },
  {
    id: 'jet-dwc-ruh-650',
    aircraftType: 'Gulfstream G650ER',
    category: 'Heavy Long-Range',
    operator: 'Empire Aviation Global',
    tailNumber: 'A6-GLF',
    departureAirportCode: 'DWC',
    departureAirportName: 'Al Maktoum International Airport',
    departureCity: 'Dubai, UAE',
    arrivalAirportCode: 'RUH',
    arrivalAirportName: 'King Khalid International Airport',
    arrivalCity: 'Riyadh, Saudi Arabia',
    departureDate: '2026-10-20',
    departureTime: '13:00 GST',
    flightDuration: '1h 45m',
    maxPassengers: 16,
    wholeJetRetailPrice: 52000,
    wholeJetMemberPrice: 16500,
    perSeatMemberPrice: 2100,
    savingsPercentage: 68,
    amenities: ['Master Stateroom Suite with En-Suite', 'Convection Oven & Arabic Gourmet Catering', 'Panoramic Gulfstream Oval Windows', 'Ultra-Quiet 41dB Cabin', 'Direct Chauffeur Ramp Access to Plane'],
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'ExecuJet VIP Terminal DWC',
    status: 'available'
  },
  {
    id: 'jet-zrh-ibz-7500',
    aircraftType: 'Bombardier Global 7500',
    category: 'Heavy Long-Range',
    operator: 'Cat Aviation AG',
    tailNumber: 'HB-JGL',
    departureAirportCode: 'ZRH',
    departureAirportName: 'Zurich Kloten Airport',
    departureCity: 'Zurich, Switzerland',
    arrivalAirportCode: 'IBZ',
    arrivalAirportName: 'Ibiza Airport',
    arrivalCity: 'Ibiza, Spain',
    departureDate: '2026-10-22',
    departureTime: '15:20 CET',
    flightDuration: '2h 00m',
    maxPassengers: 14,
    wholeJetRetailPrice: 46000,
    wholeJetMemberPrice: 14200,
    perSeatMemberPrice: 1850,
    savingsPercentage: 69,
    amenities: ['Four True Living Spaces & Master Bedroom', 'Nuage Ergonomic Deep Recline Seating', 'Soleil Circadian Rhythm Lighting', 'Full Kitchen with Espresso Bar', 'Dedicated Flight Attendant Service'],
    image: 'https://images.unsplash.com/photo-1520437358207-323b43b50729?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'Cat Aviation General Aviation Center ZRH',
    status: 'available'
  },
  {
    id: 'jet-ase-dal-900',
    aircraftType: 'Hawker 900XP',
    category: 'Midsize Jet',
    operator: 'Wheels Up Fleet',
    tailNumber: 'N922HK',
    departureAirportCode: 'ASE',
    departureAirportName: 'Aspen Pitkin County Airport',
    departureCity: 'Aspen, CO',
    arrivalAirportCode: 'DAL',
    arrivalAirportName: 'Dallas Love Field',
    arrivalCity: 'Dallas, TX',
    departureDate: '2026-10-25',
    departureTime: '12:00 MST',
    flightDuration: '2h 10m',
    maxPassengers: 8,
    wholeJetRetailPrice: 24500,
    wholeJetMemberPrice: 7800,
    perSeatMemberPrice: 1150,
    savingsPercentage: 68,
    amenities: ['Spacious Stand-Up Cabin', 'Ski & Snowboard Equipment Hold', 'Complimentary Craft Cocktails', 'Pet Friendly In-Cabin', 'Atlantic Aviation Quick Boarding'],
    image: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'Atlantic Aviation FBO Aspen',
    status: 'available'
  },
  {
    id: 'jet-teb-pbi-550',
    aircraftType: 'Gulfstream G550',
    category: 'Heavy Long-Range',
    operator: 'Executive Jet Management',
    tailNumber: 'N550XP',
    departureAirportCode: 'TEB',
    departureAirportName: 'Teterboro Executive Airport',
    departureCity: 'New York, NY',
    arrivalAirportCode: 'PBI',
    arrivalAirportName: 'Palm Beach International Airport',
    arrivalCity: 'West Palm Beach, FL',
    departureDate: '2026-10-27',
    departureTime: '10:00 EST',
    flightDuration: '2h 30m',
    maxPassengers: 14,
    wholeJetRetailPrice: 39500,
    wholeJetMemberPrice: 12900,
    perSeatMemberPrice: 1650,
    savingsPercentage: 67,
    amenities: ['Executive Conference Salon with Table', 'Lie-Flat Berthable Beds for Overnight Rest', 'High-Speed Wi-Fi & Apple TV Stream', 'Full Galley with Hot Catering', 'Direct Jet Bridge or Tarmac Escalade'],
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'Meridian FBO Teterboro',
    status: 'available'
  },
  {
    id: 'jet-xsp-dps-350',
    aircraftType: 'Bombardier Challenger 350',
    category: 'Super Midsize',
    operator: 'VistaJet Asia',
    tailNumber: '9V-VJP',
    departureAirportCode: 'XSP',
    departureAirportName: 'Seletar Airport',
    departureCity: 'Singapore',
    arrivalAirportCode: 'DPS',
    arrivalAirportName: 'Ngurah Rai International Airport',
    arrivalCity: 'Bali, Indonesia',
    departureDate: '2026-10-30',
    departureTime: '11:00 SGT',
    flightDuration: '2h 20m',
    maxPassengers: 9,
    wholeJetRetailPrice: 31000,
    wholeJetMemberPrice: 9800,
    perSeatMemberPrice: 1350,
    savingsPercentage: 68,
    amenities: ['Wide Cabin with Flat Floor Architecture', 'Fine Asian & Continental Dining Options', 'In-Flight Luggage Access', 'Starlink Ka-Band Connectivity', 'VIP Fast-Track Clearance in Bali'],
    image: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e873?auto=format&fit=crop&w=1200&q=80',
    fboTerminal: 'Universal Aviation Singapore Seletar',
    status: 'available'
  }
];`;

// 5. Expanded MOCK_CRUISES
const expandedCruisesCode = `export const MOCK_CRUISES: CruiseItinerary[] = [
  {
    id: 'icon-caribbean',
    shipName: 'Icon of the Seas',
    cruiseLine: 'Royal Caribbean',
    title: '7-Night Eastern Caribbean & Perfect Day at CocoCay',
    destination: 'Eastern Caribbean',
    departurePort: 'Miami, Florida',
    durationNights: 7,
    portsOfCall: ['Miami, FL', 'Philipsburg, St. Maarten', 'Charlotte Amalie, St. Thomas', 'Perfect Day at CocoCay, Bahamas'],
    departureDates: ['2026-10-18', '2026-11-08', '2026-12-06', '2027-01-10'],
    thumbnail: 'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 1890,
    memberPriceStarting: 1140,
    savingsPercentage: 40,
    onboardCredit: 250,
    cabins: [
      {
        id: 'balcony-ocean',
        name: 'Spacious Ocean View Balcony Stateroom',
        category: 'Balcony',
        description: 'Private glass balcony with unobstructed Caribbean ocean views, sitting area with sofa bed, and luxury bedding.',
        publicBrochurePrice: 2240,
        wholesaleMemberPrice: 1390,
        onboardCreditBonus: 250,
        freePerks: ['$250 Free Onboard Spending Credit', 'Free Premium Wi-Fi Package', 'Complimentary Specialty Dining for 2'],
        availableCount: 5,
      },
      {
        id: 'suite-sky-junior',
        name: 'Sky Class Junior Suite with Coastal Balcony',
        category: 'Suite',
        description: 'Elevated luxury suite with luxury bathroom, Lavazza espresso machine, dedicated concierge, and priority boarding.',
        publicBrochurePrice: 3850,
        wholesaleMemberPrice: 2350,
        onboardCreditBonus: 400,
        freePerks: ['$400 Free Onboard Credit', 'Suite Lounge Access & Evening Cocktails', 'Complimentary VOOM Surf & Stream Wi-Fi'],
        availableCount: 2,
      }
    ]
  },
  {
    id: 'celebrity-beyond-greece',
    shipName: 'Celebrity Beyond',
    cruiseLine: 'Celebrity Cruises',
    title: '9-Night Greek Isles, Santorini & Turkey Riviera',
    destination: 'Mediterranean',
    departurePort: 'Rome (Civitavecchia), Italy',
    durationNights: 9,
    portsOfCall: ['Civitavecchia (Rome)', 'Naples (Capri & Pompeii)', 'Santorini (Oia & Fira)', 'Mykonos, Greece', 'Ephesus (Kusadasi), Turkey', 'Athens (Piraeus)'],
    departureDates: ['2026-10-24', '2026-11-14', '2027-04-10'],
    thumbnail: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 2450,
    memberPriceStarting: 1390,
    savingsPercentage: 43,
    onboardCredit: 350,
    cabins: [
      {
        id: 'infinite-veranda',
        name: 'Edge Infinite Veranda Stateroom',
        category: 'Balcony',
        description: 'Floor-to-ceiling glass that transforms from an enclosed sunroom to an open-air balcony at the touch of a button.',
        publicBrochurePrice: 2890,
        wholesaleMemberPrice: 1680,
        onboardCreditBonus: 350,
        freePerks: ['Classic Drinks Package Included', 'Unlimited High-Speed Wi-Fi', '$350 Onboard Spending Cash'],
        availableCount: 4,
      },
      {
        id: 'retreat-suite',
        name: 'The Retreat Celebrity Penthouse Suite',
        category: 'Suite',
        description: 'Ultra-exclusive keycard enclave with private sun deck, pool, dedicated restaurant Luminae, and 24/7 personal butler.',
        publicBrochurePrice: 5900,
        wholesaleMemberPrice: 3500,
        onboardCreditBonus: 600,
        freePerks: ['Premium Drinks & Champagne Included', 'Access to The Retreat Lounge & Deck', 'Complimentary In-Suite Minibar & Caviar'],
        availableCount: 1,
      }
    ]
  },
  {
    id: 'utopia-bahamas-coco',
    shipName: 'Utopia of the Seas',
    cruiseLine: 'Royal Caribbean',
    title: '4-Night Weekend Bahamas & CocoCay Thrill',
    destination: 'Eastern Caribbean',
    departurePort: 'Port Canaveral (Orlando), Florida',
    durationNights: 4,
    portsOfCall: ['Port Canaveral, FL', 'Nassau, Bahamas', 'Perfect Day at CocoCay, Bahamas'],
    departureDates: ['2026-10-16', '2026-10-23', '2026-11-06', '2026-11-20'],
    thumbnail: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 980,
    memberPriceStarting: 540,
    savingsPercentage: 45,
    onboardCredit: 150,
    cabins: [
      {
        id: 'ocean-balcony-utopia',
        name: 'Ocean View Balcony Stateroom',
        category: 'Balcony',
        description: 'Wake up to the turquoise Bahamian waters. Private glass balcony with sun chairs, luxury bedding, and smart TV.',
        publicBrochurePrice: 1250,
        wholesaleMemberPrice: 690,
        onboardCreditBonus: 150,
        freePerks: ['$150 Free Onboard Credit', 'CocoCay Waterpark Pass Included', 'Free High-Speed Wi-Fi'],
        availableCount: 8,
      }
    ]
  },
  {
    id: 'norwegian-prima-fjords',
    shipName: 'Norwegian Prima',
    cruiseLine: 'Norwegian Cruise Line',
    title: '10-Night Northern Europe & Norwegian Fjords Masterpiece',
    destination: 'Mediterranean',
    departurePort: 'Southampton (London), UK',
    durationNights: 10,
    portsOfCall: ['Southampton (London)', 'Zeebrugge (Brussels)', 'Amsterdam, Netherlands', 'Bergen, Norway', 'Geiranger Fjord', 'Alesund', 'Oslo, Norway'],
    departureDates: ['2026-10-20', '2026-11-10', '2027-05-15'],
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 2890,
    memberPriceStarting: 1620,
    savingsPercentage: 44,
    onboardCredit: 400,
    cabins: [
      {
        id: 'haven-penthouse',
        name: 'The Haven Courtyard Penthouse Balcony',
        category: 'Suite',
        description: 'The Haven private ship-within-a-ship access. 24-hour certified butler, private Haven sundeck and infinity pool over the ship wake.',
        publicBrochurePrice: 4800,
        wholesaleMemberPrice: 2850,
        onboardCreditBonus: 400,
        freePerks: ['Free Open Bar Beverage Package', 'Free Specialty Dining Package', 'Free Shore Excursion Credits', '$400 Onboard Cash'],
        availableCount: 2,
      }
    ]
  },
  {
    id: 'celebrity-edge-alaska',
    shipName: 'Celebrity Edge',
    cruiseLine: 'Celebrity Cruises',
    title: '7-Night Alaska Dawes Glacier & Inside Passage Expedition',
    destination: 'Alaska',
    departurePort: 'Seattle, Washington',
    durationNights: 7,
    portsOfCall: ['Seattle, WA', 'Ketchikan, AK', 'Endicott Arm & Dawes Glacier', 'Juneau, AK', 'Skagway, AK', 'Victoria, BC Canada'],
    departureDates: ['2026-10-10', '2027-05-08', '2027-06-12'],
    thumbnail: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 2100,
    memberPriceStarting: 1180,
    savingsPercentage: 44,
    onboardCredit: 300,
    cabins: [
      {
        id: 'infinite-veranda-alaska',
        name: 'Infinite Veranda with Glacier Views',
        category: 'Balcony',
        description: 'Sit in your climate-controlled private balcony and watch towering tidewater glaciers and breaching humpback whales.',
        publicBrochurePrice: 2450,
        wholesaleMemberPrice: 1380,
        onboardCreditBonus: 300,
        freePerks: ['Complimentary Glacier Binoculars & Parka Service', 'Classic Beverage Package', 'Unlimited Wi-Fi Package'],
        availableCount: 6,
      }
    ]
  },
  {
    id: 'virgin-scarlet-ibiza',
    shipName: 'Scarlet Lady',
    cruiseLine: 'Royal Caribbean',
    title: '7-Night French Daze & Ibiza Nights (Adults Only)',
    destination: 'Mediterranean',
    departurePort: 'Barcelona, Spain',
    durationNights: 7,
    portsOfCall: ['Barcelona, Spain', 'Marseille, France', 'Cannes, France', 'Palma de Mallorca', 'Ibiza, Spain (Overnight Port Stay)'],
    departureDates: ['2026-10-18', '2026-11-01', '2027-05-02'],
    thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 2250,
    memberPriceStarting: 1280,
    savingsPercentage: 43,
    onboardCredit: 300,
    cabins: [
      {
        id: 'sea-terrace-hammock',
        name: 'Sea Terrace with Handwoven Red Hammock',
        category: 'Balcony',
        description: 'Handwoven Yellow Leaf terrace hammock, transformable seabed lounge, mood lighting, and rain shower with Red Flower amenities.',
        publicBrochurePrice: 2600,
        wholesaleMemberPrice: 1480,
        onboardCreditBonus: 300,
        freePerks: ['All 20+ Eateries Included (No Buffet)', 'All Gratuities & Tips Covered', '$300 Sailor Loot Bar Tab'],
        availableCount: 5,
      }
    ]
  },
  {
    id: 'symphony-mediterranean',
    shipName: 'Symphony of the Seas',
    cruiseLine: 'Royal Caribbean',
    title: '7-Night Western Mediterranean Masterpiece',
    destination: 'Mediterranean',
    departurePort: 'Barcelona, Spain',
    durationNights: 7,
    portsOfCall: ['Barcelona, Spain', 'Palma de Mallorca', 'Provence (Marseille)', 'Florence / Pisa (La Spezia)', 'Rome (Civitavecchia)', 'Naples (Capri)'],
    departureDates: ['2026-10-25', '2026-11-15', '2027-04-18'],
    thumbnail: 'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 1850,
    memberPriceStarting: 1090,
    savingsPercentage: 41,
    onboardCredit: 250,
    cabins: [
      {
        id: 'balcony-symphony',
        name: 'Central Park View or Ocean Balcony Stateroom',
        category: 'Balcony',
        description: 'Choose between overlooking living gardens in Central Park or unobstructed views of the Mediterranean Sea.',
        publicBrochurePrice: 2150,
        wholesaleMemberPrice: 1280,
        onboardCreditBonus: 250,
        freePerks: ['$250 Onboard Spending Cash', 'Deluxe Beverage Package Discount', 'Surf & Stream Internet'],
        availableCount: 7,
      }
    ]
  },
  {
    id: 'princess-sun-adriatic',
    shipName: 'Sun Princess',
    cruiseLine: 'Princess',
    title: '10-Night Mediterranean & Adriatic Enchantment',
    destination: 'Mediterranean',
    departurePort: 'Athens (Piraeus), Greece',
    durationNights: 10,
    portsOfCall: ['Athens, Greece', 'Santorini', 'Kotor, Montenegro', 'Corfu, Greece', 'Messina (Sicily)', 'Naples', 'Rome (Civitavecchia)'],
    departureDates: ['2026-10-22', '2026-11-12', '2027-04-22'],
    thumbnail: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1200&q=80'
    ],
    publicPriceStarting: 2580,
    memberPriceStarting: 1420,
    savingsPercentage: 45,
    onboardCredit: 350,
    cabins: [
      {
        id: 'deluxe-balcony-princess',
        name: 'Deluxe Balcony with Signature Princess Luxury Bed',
        category: 'Balcony',
        description: 'Signature luxury bed developed by sleep doctors, floor-to-ceiling glass sliding doors, and private terrace.',
        publicBrochurePrice: 2950,
        wholesaleMemberPrice: 1650,
        onboardCreditBonus: 350,
        freePerks: ['Princess Plus: Drinks, Wi-Fi & Crew Appreciation Included', '$350 Onboard Spending Credit'],
        availableCount: 4,
      }
    ]
  }
];`;

// Replacement 1: MOCK_VILLAS
const villasRegex = /export const MOCK_VILLAS: LuxuryVillaEstate\[\] = \[[\s\S]*?\];/;
if (villasRegex.test(content)) {
  content = content.replace(villasRegex, expandedVillasCode);
  console.log('✓ Replaced MOCK_VILLAS with 12 world-class luxury estates');
} else {
  console.error('Failed to match MOCK_VILLAS');
}

// Replacement 2: MOCK_YACHTS
const yachtsRegex = /export const MOCK_YACHTS: LuxuryYachtCharter\[\] = \[[\s\S]*?\];/;
if (yachtsRegex.test(content)) {
  content = content.replace(yachtsRegex, expandedYachtsCode);
  console.log('✓ Replaced MOCK_YACHTS with 5 mega-yachts');
} else {
  console.error('Failed to match MOCK_YACHTS');
}

// Replacement 3: MOCK_SUPERCARS
const supercarsRegex = /export const MOCK_SUPERCARS: SupercarRental\[\] = \[[\s\S]*?\];/;
if (supercarsRegex.test(content)) {
  content = content.replace(supercarsRegex, expandedSupercarsCode);
  console.log('✓ Replaced MOCK_SUPERCARS with 5 supercars');
} else {
  console.error('Failed to match MOCK_SUPERCARS');
}

// Replacement 4: MOCK_PRIVATE_JETS
const jetsRegex = /export const MOCK_PRIVATE_JETS: PrivateJetEmptyLeg\[\] = \[[\s\S]*?\];/;
if (jetsRegex.test(content)) {
  content = content.replace(jetsRegex, expandedJetsCode);
  console.log('✓ Replaced MOCK_PRIVATE_JETS with 10 real empty leg routes');
} else {
  console.error('Failed to match MOCK_PRIVATE_JETS');
}

// Replacement 5: MOCK_CRUISES
const cruisesRegex = /export const MOCK_CRUISES: CruiseItinerary\[\] = \[[\s\S]*?\];/;
if (cruisesRegex.test(content)) {
  content = content.replace(cruisesRegex, expandedCruisesCode);
  console.log('✓ Replaced MOCK_CRUISES with 8 luxury cruise itineraries');
} else {
  console.error('Failed to match MOCK_CRUISES');
}

fs.writeFileSync(mockDataPath, content, 'utf8');
console.log('Successfully updated mockData.ts!');
